// Package juvuln provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package juvuln

const (
	BasicAuthScopes = "BasicAuth.Scopes"
)

// Defines values for NewSubscriberScheme.
const (
	NewSubscriberSchemeHttp  NewSubscriberScheme = "http"
	NewSubscriberSchemeHttps NewSubscriberScheme = "https"
)

// Valid indicates whether the value is a known member of the NewSubscriberScheme enum.
func (e NewSubscriberScheme) Valid() bool {
	switch e {
	case NewSubscriberSchemeHttp:
		return true
	case NewSubscriberSchemeHttps:
		return true
	default:
		return false
	}
}

// Defines values for WorkerSubscribeJSONBodyScheme.
const (
	WorkerSubscribeJSONBodySchemeHttp  WorkerSubscribeJSONBodyScheme = "http"
	WorkerSubscribeJSONBodySchemeHttps WorkerSubscribeJSONBodyScheme = "https"
)

// Valid indicates whether the value is a known member of the WorkerSubscribeJSONBodyScheme enum.
func (e WorkerSubscribeJSONBodyScheme) Valid() bool {
	switch e {
	case WorkerSubscribeJSONBodySchemeHttp:
		return true
	case WorkerSubscribeJSONBodySchemeHttps:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code int `json:"code"`

	// Message Error message
	Message string `json:"message"`
}

// DomainPathParam defines model for domainPathParam.
type DomainPathParam = string

// DomainQueryParam defines model for domainQueryParam.
type DomainQueryParam = string

// LanguageParam defines model for languageParam.
type LanguageParam = string

// ModuleParam defines model for moduleParam.
type ModuleParam = string

// RevisionParam defines model for revisionParam.
type RevisionParam = string

// UuidParam defines model for uuidParam.
type UuidParam = string

// BadGateway defines model for BadGateway.
type BadGateway = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// NewSubscriber defines model for NewSubscriber.
type NewSubscriber struct {
	// Authority On the format [userinfo@]host[:port].
	Authority string `json:"authority"`

	// Languages A list of supported languages.
	Languages []string            `json:"languages"`
	Scheme    NewSubscriberScheme `json:"scheme"`
	Uuid      string              `json:"uuid"`
}

// NewSubscriberScheme defines model for NewSubscriber.Scheme.
type NewSubscriberScheme string

// UpdateLoad defines model for UpdateLoad.
type UpdateLoad struct {
	Load int64 `json:"load"`
}

// GetModuleAtRevisionParams defines parameters for GetModuleAtRevision.
type GetModuleAtRevisionParams struct {
	// Domain A domain
	Domain DomainQueryParam `form:"domain" json:"domain"`

	// Module The module name
	Module ModuleParam `form:"module" json:"module"`

	// Language The language of the module
	Language LanguageParam `form:"language" json:"language"`

	// Revision The module revision. The keyword 'latest' will return the latest revision.
	Revision RevisionParam `form:"revision" json:"revision"`
}

// WorkerSubscribeJSONBody defines parameters for WorkerSubscribe.
type WorkerSubscribeJSONBody struct {
	// Authority On the format [userinfo@]host[:port].
	Authority string `json:"authority"`

	// Languages A list of supported languages.
	Languages []string                      `json:"languages"`
	Scheme    WorkerSubscribeJSONBodyScheme `json:"scheme"`
	Uuid      string                        `json:"uuid"`
}

// WorkerSubscribeJSONBodyScheme defines parameters for WorkerSubscribe.
type WorkerSubscribeJSONBodyScheme string

// WorkerLoadUpdateJSONBody defines parameters for WorkerLoadUpdate.
type WorkerLoadUpdateJSONBody struct {
	Load int64 `json:"load"`
}

// WorkerSubscribeJSONRequestBody defines body for WorkerSubscribe for application/json ContentType.
type WorkerSubscribeJSONRequestBody WorkerSubscribeJSONBody

// WorkerLoadUpdateJSONRequestBody defines body for WorkerLoadUpdate for application/json ContentType.
type WorkerLoadUpdateJSONRequestBody WorkerLoadUpdateJSONBody
