// Package juvuln provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package juvuln

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get module
	// (GET /v1/library)
	GetModuleAtRevision(w http.ResponseWriter, r *http.Request, params GetModuleAtRevisionParams)
	// Subscribe as a worker.
	// (POST /v1/subscribers)
	WorkerSubscribe(w http.ResponseWriter, r *http.Request)
	// Unsubscribe as a worker
	// (DELETE /v1/subscribers/{uuid})
	WorkerUnsubscribe(w http.ResponseWriter, r *http.Request, uuid UuidParam)
	// Check if subscriber has been added
	// (GET /v1/subscribers/{uuid})
	CheckWorker(w http.ResponseWriter, r *http.Request, uuid UuidParam)
	// Update Load Data
	// (PUT /v1/subscribers/{uuid}/load)
	WorkerLoadUpdate(w http.ResponseWriter, r *http.Request, uuid UuidParam)
	// Proxy interface for webhooks
	// (POST /v1/webhooks/{domain}/{uuid})
	ForwardWebhook(w http.ResponseWriter, r *http.Request, domain DomainPathParam, uuid UuidParam)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get module
// (GET /v1/library)
func (_ Unimplemented) GetModuleAtRevision(w http.ResponseWriter, r *http.Request, params GetModuleAtRevisionParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Subscribe as a worker.
// (POST /v1/subscribers)
func (_ Unimplemented) WorkerSubscribe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Unsubscribe as a worker
// (DELETE /v1/subscribers/{uuid})
func (_ Unimplemented) WorkerUnsubscribe(w http.ResponseWriter, r *http.Request, uuid UuidParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Check if subscriber has been added
// (GET /v1/subscribers/{uuid})
func (_ Unimplemented) CheckWorker(w http.ResponseWriter, r *http.Request, uuid UuidParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update Load Data
// (PUT /v1/subscribers/{uuid}/load)
func (_ Unimplemented) WorkerLoadUpdate(w http.ResponseWriter, r *http.Request, uuid UuidParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Proxy interface for webhooks
// (POST /v1/webhooks/{domain}/{uuid})
func (_ Unimplemented) ForwardWebhook(w http.ResponseWriter, r *http.Request, domain DomainPathParam, uuid UuidParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetModuleAtRevision operation middleware
func (siw *ServerInterfaceWrapper) GetModuleAtRevision(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetModuleAtRevisionParams

	// ------------- Required query parameter "domain" -------------

	if paramValue := r.URL.Query().Get("domain"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "domain"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "domain", r.URL.Query(), &params.Domain, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "domain", Err: err})
		return
	}

	// ------------- Required query parameter "module" -------------

	if paramValue := r.URL.Query().Get("module"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "module"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "module", r.URL.Query(), &params.Module, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "module", Err: err})
		return
	}

	// ------------- Required query parameter "language" -------------

	if paramValue := r.URL.Query().Get("language"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "language"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "language", r.URL.Query(), &params.Language, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "language", Err: err})
		return
	}

	// ------------- Required query parameter "revision" -------------

	if paramValue := r.URL.Query().Get("revision"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "revision"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "revision", r.URL.Query(), &params.Revision, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "revision", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetModuleAtRevision(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// WorkerSubscribe operation middleware
func (siw *ServerInterfaceWrapper) WorkerSubscribe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WorkerSubscribe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// WorkerUnsubscribe operation middleware
func (siw *ServerInterfaceWrapper) WorkerUnsubscribe(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid UuidParam

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", chi.URLParam(r, "uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WorkerUnsubscribe(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CheckWorker operation middleware
func (siw *ServerInterfaceWrapper) CheckWorker(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid UuidParam

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", chi.URLParam(r, "uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CheckWorker(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// WorkerLoadUpdate operation middleware
func (siw *ServerInterfaceWrapper) WorkerLoadUpdate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid UuidParam

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", chi.URLParam(r, "uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WorkerLoadUpdate(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ForwardWebhook operation middleware
func (siw *ServerInterfaceWrapper) ForwardWebhook(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "domain" -------------
	var domain DomainPathParam

	err = runtime.BindStyledParameterWithOptions("simple", "domain", chi.URLParam(r, "domain"), &domain, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "domain", Err: err})
		return
	}

	// ------------- Path parameter "uuid" -------------
	var uuid UuidParam

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", chi.URLParam(r, "uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ForwardWebhook(w, r, domain, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/library", wrapper.GetModuleAtRevision)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/subscribers", wrapper.WorkerSubscribe)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/subscribers/{uuid}", wrapper.WorkerUnsubscribe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/subscribers/{uuid}", wrapper.CheckWorker)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/v1/subscribers/{uuid}/load", wrapper.WorkerLoadUpdate)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/webhooks/{domain}/{uuid}", wrapper.ForwardWebhook)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RYX3PbuBH/KijSmXuhSMnWObY6nYnT9DKe8+XcuB4/uHqAyKWImgQY/LGiavjdOwuQ",
	"FGVStuykaftkC1gsfrv72z/ghsayKKUAYTSdbWjJFCvAgHK/ElkwLq6Yya5w3S2BjhUvDZeCzug58SI0",
	"oBx/l8xkNKCCFUBntN1T8MVyBQmdGWUhoDrOoGCoDr6yosxROJWSBtSsS/yhjeJiSasqqJX8zYJaHwji",
	"C8p+ZxQ5E0vLlrAHwt8zII0IkSkxGZBCJjaHPaAa4QNhGRDLYWD+lidgeQHi7h3G0gI9BEmxzvliEImC",
	"B665FM9jaSRDgov3sF5JlZCfcmZAm5/Iiuc5UWCsEs6Rfn17ao8Zzf6BhhzRgBZcXIJYmozOJkMmWcuT",
	"J8xRoKVVMZCbm4sPwymAGg4ENDk9OxlPT+PRIonPRtPjeDpi6XQymrKz6cnijB1PJzDg+MprB23ey4SD",
	"y9tPsLq2C4S7AIULsRQGhMF/WVnmPGZoRvRPjbZsOnBKJUtQptbDrMmk4mbdt/93H5tUqoIZcmc1KC5S",
	"+W6eSW3uZqVUZo6R2tqHIrOSaf1uMg7H4eTobTg5m52O+zZt000PZXvOtcEk07bEayBpU087bhgo9EHp",
	"0y4wpdgafztHgDssbEFndzQzpqSB+6PpvGtPvdPT6UL+PSLbpc1dw6QaYdCJTdddc0eIXY/VVHA/CQYJ",
	"Q1Yn0i4xq4DelAkzcClZ8g28yevjrQsmR8fTn08C6u+mM8qFOZlubebCwBJUz2inaMimW6nuQRHcJwqQ",
	"Buiznj1OnS6l0B7Ye5Z8ZAZWbP0i6/6oIKUz+ibaNsvI7+ror0pJRQcgXogHlnOE5wGQVMmC2FIbBawg",
	"GtQDqBAZ8wFyMJDsKzIuubfFZsU0SfwJd/pCGFCC5ddOoYfzA4zzl9ZmEPCCAf0kzS/SiuQ/DwGdo0uI",
	"ecoh2XWPkIakiMI56Pdf+569tnEMWrv9G1Hn0r8g+XG0wDtBmFo7iRUk+JPlNSiXhy/hhPUnQpdENQw8",
	"3jJiN0djmUBfuxMmbq+fnAEtQGucWvaca7afq2W1/kZ87hBDbLGcXbsCV2er5vG5xfa8aUszXeDq9gpX",
	"hp2fsbT1kb15Q24hj2UBxEjXs2Sa8piznCQytgUI4yNQj23XkKcjbGLkSsmlYgX5jQm2BEXOry7Cf+B4",
	"kfMYhHZeqNv8x6vL0XE4HkmRYz22Kq+R6VkUyRKEj1Mo1TKqT+uoPuT6EDeuUzx5OQ3oAyjtzRqHE38U",
	"tbOS0xk9DschdlOcQJz/oodJlPOFYsqVuyWYvns+gnFm10TCyGBTJ6wZ1t6RzmCFBHLeukj82d+c0Ln5",
	"3B2+OgX3aDx+lFIGvpqozBkXfyJxxpQG82dr0tHpbm61nWLBBXNj3sDg82gk+RX9MR1P9+Vmiyxqq5Rj",
	"ni0K5yLnjHYaNmypXQ+qPTivgp3n0d3wJVuRqPd0qYJnz3Tn+QPEd98lBxzYndIrNAppottx0T8DpR7g",
	"ypU1pADCBYkli7M/9Ajhu3I7etLuaLreH5XO9Brtjq5Vj06T54Pb8OAA0Z3SXwX0Z0/Xpw8NNdxdHrUW",
	"EKYJIyvnlrDDqdbdvvY9ikC0wWGv8gHARt8PxY3QQ3fsiUhHup+gB6RLM6C81q0vzMnvFof9XhoKRDBc",
	"If+SQXxPtuEJyY2GhCzWrT7CDGE4WhtQDyzHPgNCWwXEZMyX16Iu4/dCrjRhC2kN4SYkF6kbVlCk1uVe",
	"v+1tYS+iDs5tY8fLY/kN2fHfCqOPAE87QSAZ02QBIAhLEkj2RvRlBXv73h8qjHVaRs3r5vW6A1raAaZ9",
	"koan6x2+eKbgSmyVAmHck2dPmuOrzc+Nr6m8nZdf9RpiNRPr/12RcLgJGk4+MMOeLtMrWGRS3uto47t7",
	"1SnWr5kOth9XD2jejzg03KSV/Lr2tShlsR/mGtAh+UWqFVOJ9pRiuStW2zom3Gs656DJipvMSTW+7Jei",
	"Wtmt1/64Gv2vkwDPHj1/tvPJwE2cKbP5gNvfQ8ysxorPNeHYa0oXiDrHgh1XkpgJgj1JrE3GxTJ8RMmn",
	"YtihZ71UfyBpHlCOe52n090cyeLf6Z6Y/nmyKZU0MpZ5NYuijd+v8I3BFGeL3AexkfEG17Y3n756xPOi",
	"wZ6PZ1WDYlfZ5Oht6D4Izk7HZ297an3MyM3nS5z55631m6e+coFISsmF0dsvsdtcrubVvwMAAP//adnC",
	"UPcYAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
