// Package malgomaj provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package malgomaj

const (
	BasicAuthScopes = "BasicAuth.Scopes"
)

// Defines values for NewTaskLanguage.
const (
	NewTaskLanguageTengo NewTaskLanguage = "tengo"
)

// Valid indicates whether the value is a known member of the NewTaskLanguage enum.
func (e NewTaskLanguage) Valid() bool {
	switch e {
	case NewTaskLanguageTengo:
		return true
	default:
		return false
	}
}

// Defines values for CreateTaskJSONBodyLanguage.
const (
	CreateTaskJSONBodyLanguageTengo CreateTaskJSONBodyLanguage = "tengo"
)

// Valid indicates whether the value is a known member of the CreateTaskJSONBodyLanguage enum.
func (e CreateTaskJSONBodyLanguage) Valid() bool {
	switch e {
	case CreateTaskJSONBodyLanguageTengo:
		return true
	default:
		return false
	}
}

// Status defines model for Status.
type Status struct {
	// Load The current load (aggregated deadlines)
	Load int64 `json:"load"`
}

// NewTask defines model for NewTask.
type NewTask struct {
	Deadline int    `json:"deadline"`
	Domain   string `json:"domain"`

	// Http Optional. When in use the task is executed as a HTTP procedure.
	Http *struct {
		Body    []byte            `json:"body"`
		Headers map[string]string `json:"headers"`
	} `json:"http,omitempty"`
	Language    NewTaskLanguage `json:"language"`
	ProgramUuid string          `json:"program_uuid"`
	SourceCode  []byte          `json:"source_code"`
}

// NewTaskLanguage defines model for NewTask.Language.
type NewTaskLanguage string

// CreateTaskJSONBody defines parameters for CreateTask.
type CreateTaskJSONBody struct {
	Deadline int    `json:"deadline"`
	Domain   string `json:"domain"`

	// Http Optional. When in use the task is executed as a HTTP procedure.
	Http *struct {
		Body    []byte            `json:"body"`
		Headers map[string]string `json:"headers"`
	} `json:"http,omitempty"`
	Language    CreateTaskJSONBodyLanguage `json:"language"`
	ProgramUuid string                     `json:"program_uuid"`
	SourceCode  []byte                     `json:"source_code"`
}

// CreateTaskJSONBodyLanguage defines parameters for CreateTask.
type CreateTaskJSONBodyLanguage string

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody CreateTaskJSONBody
