// Package malgomaj provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package malgomaj

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get worker status
	// (GET /v1/status)
	GetStatus(w http.ResponseWriter, r *http.Request)
	// Add a new Task
	// (POST /v1/tasks)
	CreateTask(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get worker status
// (GET /v1/status)
func (_ Unimplemented) GetStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a new Task
// (POST /v1/tasks)
func (_ Unimplemented) CreateTask(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetStatus operation middleware
func (siw *ServerInterfaceWrapper) GetStatus(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTask operation middleware
func (siw *ServerInterfaceWrapper) CreateTask(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTask(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/status", wrapper.GetStatus)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/tasks", wrapper.CreateTask)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xWX2/bNhD/Kgd2Dy0gS7KTuJne0qHrinVtsKTIgMwozuRZYiORGknF8QJ/94GkZMd/",
	"0q1vezIt3h3vfve7P4+M66bVipSzrHhkFaEgE45/jN4+tNJQ+CPIciNbJ7ViBbtQ8Mv19eVIoCNwsiHr",
	"sGlTljB6wKatiRVb9QJuSCQwGcMn7mCSj88gf11Mzos8h3e/XbOEWV5Rg/4Zt2q9rnVGqpKt1+uEGfqr",
	"I+veaCGjKx9peY32zh+5Vo6U80ds21py9A5mX6338vGJ3dboloyTQzAoaqnInzcOn+V5nrAGH2TTNayY",
	"5vG/VPF/ngzOSeWoJMPWCRO6Qal2zLBm1X9N9qNJWOVce4jmp3DAOoWbihRIBZ0lcBWBQ3sH0gI9EO8c",
	"CUALGKCH1mhOojPkUd8Nb67Fyv8utGnQsYLNV46OurNNNgohoxeXO7YOdPoPev6VuGNDgqQhwYrbjcUk",
	"OjE7kE9YjarssIzgKw/tLXOkSu2ltzDGT0ecbo0uDTZfuk6KXeTxbEI4PhcjPMHz0Wk+H49wTuejk8nk",
	"fEo0XUznYxZS/IFU6SpWnExDhp/+PXjP6s5w+sK1oP8A6h4eG6ZtuPIEgL1Ydp+aBfLvEsXTHpwGtFaW",
	"yp88SZba3JHxNNi+7ExH0RfbamVjLn/WZi6FIHVIwY/aAda1XpLwZlsyPs5gHrmXST0U75Ujo7C+InNP",
	"5q0x2hyaGoTABimgILZO2GeFnau0kX+TOKZ2j7UU4GVIub6UgRsS/i/WNg3oxpoO8Vw5dJ09LO9a45EH",
	"risC3hlDyoGXgJdYloZK9HU15Mm+etrDTpNtuqVy01P27Yawl/zgxyw4Tbwz0q2uvPPRyTdoJb/oPO36",
	"RuVNzf3XLatCvwhEkGqhD2N68QJuqOa6oYEMerGQXGINQvOuIeUijHoRbq+oXowqbR1cRubBTSAPXFy+",
	"T/8M5JSclA1MVxhcenf5YXSS5iOt6hVLWGfq3jFbZJluSUXWptqUWa9ts14pNAzpQnV+622WsHsyNgaV",
	"p+Oo6Y1jK1nBTtI8zX29oKsCetn9OLOb9JfkDrF5Rw56kWDKBCTei3h1NdzsVMgkz79rrPxgaOHTkG2H",
	"aNYTNOtfOFLGn3710Z3m4+dMbHzKdmomKJ38u9K2ztcJO4shfVvjWGE/5S0rbncYe8vYbD1LmO2aBs2q",
	"Rzs2oi3oDkvrZfsPoRJ84vxUi2Wr7ZHEXQgBCIqWEMb8fvJ+MoSO+qvtcrB6Pson+0M2LA/r45nf9eSq",
	"45ysTeECXnqLsibxCvqm7ecyR16RgE45WYcC8wvRyC9EYFviciFJwHwVrjb7EMQh6a32+oPFpaxrmBMY",
	"6iwJWEpX6c5B7ClSlWAourFT1Lwifme7Bhp0vCLrJ8Fza9wxgHrZbCsYOPu/56cvqwV29REKhT0qLk0e",
	"NtwgHPanJc0rre+gZ0YSUBweA47K5wDVylVSlel3FsIBe4cqiKyPY/1Zc9FYiNKGy9huH1ujnea6XhdZ",
	"9hjv175popE4r2kYgkEmwtEjE0fIfge6HESTzQrWy4XGzmbrwYtdY+PJa9+J03Fxnv84PTAb0wOff//g",
	"KTTbxL6fnjT1HO3nS8RlPVv/EwAA//+dBd1giwwAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
