// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package rest

import (
	"time"
)

const (
	BasicAuthScopes = "BasicAuth.Scopes"
)

// Defines values for AlertSeverity.
const (
	Critical      AlertSeverity = "critical"
	Debug         AlertSeverity = "debug"
	Indeterminate AlertSeverity = "indeterminate"
	Informational AlertSeverity = "informational"
	Major         AlertSeverity = "major"
	Minor         AlertSeverity = "minor"
	Security      AlertSeverity = "security"
	Trace         AlertSeverity = "trace"
	Warning       AlertSeverity = "warning"
)

// Valid indicates whether the value is a known member of the AlertSeverity enum.
func (e AlertSeverity) Valid() bool {
	switch e {
	case Critical:
		return true
	case Debug:
		return true
	case Indeterminate:
		return true
	case Informational:
		return true
	case Major:
		return true
	case Minor:
		return true
	case Security:
		return true
	case Trace:
		return true
	case Warning:
		return true
	default:
		return false
	}
}

// Defines values for AlertStatus.
const (
	Acknowledge AlertStatus = "acknowledge"
	Close       AlertStatus = "close"
	Expire      AlertStatus = "expire"
	Open        AlertStatus = "open"
	Shelve      AlertStatus = "shelve"
	Unknown     AlertStatus = "unknown"
)

// Valid indicates whether the value is a known member of the AlertStatus enum.
func (e AlertStatus) Valid() bool {
	switch e {
	case Acknowledge:
		return true
	case Close:
		return true
	case Expire:
		return true
	case Open:
		return true
	case Shelve:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for AuthorizationDecisionAction.
const (
	AuthorizationDecisionActionCreate AuthorizationDecisionAction = "create"
	AuthorizationDecisionActionDelete AuthorizationDecisionAction = "delete"
	AuthorizationDecisionActionRead   AuthorizationDecisionAction = "read"
	AuthorizationDecisionActionUpdate AuthorizationDecisionAction = "update"
)

// Valid indicates whether the value is a known member of the AuthorizationDecisionAction enum.
func (e AuthorizationDecisionAction) Valid() bool {
	switch e {
	case AuthorizationDecisionActionCreate:
		return true
	case AuthorizationDecisionActionDelete:
		return true
	case AuthorizationDecisionActionRead:
		return true
	case AuthorizationDecisionActionUpdate:
		return true
	default:
		return false
	}
}

// Defines values for AuthorizationDecisionEffect.
const (
	AuthorizationDecisionEffectAllow AuthorizationDecisionEffect = "allow"
	AuthorizationDecisionEffectDeny  AuthorizationDecisionEffect = "deny"
)

// Valid indicates whether the value is a known member of the AuthorizationDecisionEffect enum.
func (e AuthorizationDecisionEffect) Valid() bool {
	switch e {
	case AuthorizationDecisionEffectAllow:
		return true
	case AuthorizationDecisionEffectDeny:
		return true
	default:
		return false
	}
}

// Defines values for DatasetFormat.
const (
	DatasetFormatCsv  DatasetFormat = "csv"
	DatasetFormatIni  DatasetFormat = "ini"
	DatasetFormatJson DatasetFormat = "json"
	DatasetFormatMisc DatasetFormat = "misc"
	DatasetFormatToml DatasetFormat = "toml"
	DatasetFormatXml  DatasetFormat = "xml"
	DatasetFormatYaml DatasetFormat = "yaml"
)

// Valid indicates whether the value is a known member of the DatasetFormat enum.
func (e DatasetFormat) Valid() bool {
	switch e {
	case DatasetFormatCsv:
		return true
	case DatasetFormatIni:
		return true
	case DatasetFormatJson:
		return true
	case DatasetFormatMisc:
		return true
	case DatasetFormatToml:
		return true
	case DatasetFormatXml:
		return true
	case DatasetFormatYaml:
		return true
	default:
		return false
	}
}

// Defines values for PolicyAction.
const (
	PolicyActionCreate PolicyAction = "create"
	PolicyActionDelete PolicyAction = "delete"
	PolicyActionRead   PolicyAction = "read"
	PolicyActionUpdate PolicyAction = "update"
)

// Valid indicates whether the value is a known member of the PolicyAction enum.
func (e PolicyAction) Valid() bool {
	switch e {
	case PolicyActionCreate:
		return true
	case PolicyActionDelete:
		return true
	case PolicyActionRead:
		return true
	case PolicyActionUpdate:
		return true
	default:
		return false
	}
}

// Defines values for PolicyEffect.
const (
	PolicyEffectAllow PolicyEffect = "allow"
	PolicyEffectDeny  PolicyEffect = "deny"
)

// Valid indicates whether the value is a known member of the PolicyEffect enum.
func (e PolicyEffect) Valid() bool {
	switch e {
	case PolicyEffectAllow:
		return true
	case PolicyEffectDeny:
		return true
	default:
		return false
	}
}

// Defines values for ProgramLanguage.
const (
	ProgramLanguageTengo ProgramLanguage = "tengo"
)

// Valid indicates whether the value is a known member of the ProgramLanguage enum.
func (e ProgramLanguage) Valid() bool {
	switch e {
	case ProgramLanguageTengo:
		return true
	default:
		return false
	}
}

// Defines values for ProgramState.
const (
	ProgramStateActive   ProgramState = "active"
	ProgramStateFailed   ProgramState = "failed"
	ProgramStateInactive ProgramState = "inactive"
)

// Valid indicates whether the value is a known member of the ProgramState enum.
func (e ProgramState) Valid() bool {
	switch e {
	case ProgramStateActive:
		return true
	case ProgramStateFailed:
		return true
	case ProgramStateInactive:
		return true
	default:
		return false
	}
}

// Defines values for ProgramType.
const (
	ProgramTypeModule  ProgramType = "module"
	ProgramTypeRoutine ProgramType = "routine"
	ProgramTypeWebhook ProgramType = "webhook"
)

// Valid indicates whether the value is a known member of the ProgramType enum.
func (e ProgramType) Valid() bool {
	switch e {
	case ProgramTypeModule:
		return true
	case ProgramTypeRoutine:
		return true
	case ProgramTypeWebhook:
		return true
	default:
		return false
	}
}

// Defines values for ThingState.
const (
	ThingStateActive   ThingState = "active"
	ThingStateArchived ThingState = "archived"
	ThingStateInactive ThingState = "inactive"
	ThingStatePassive  ThingState = "passive"
)

// Valid indicates whether the value is a known member of the ThingState enum.
func (e ThingState) Valid() bool {
	switch e {
	case ThingStateActive:
		return true
	case ThingStateArchived:
		return true
	case ThingStateInactive:
		return true
	case ThingStatePassive:
		return true
	default:
		return false
	}
}

// Defines values for AggregateParam.
const (
	AggregateParamAvg   AggregateParam = "avg"
	AggregateParamCount AggregateParam = "count"
	AggregateParamMax   AggregateParam = "max"
	AggregateParamMin   AggregateParam = "min"
	AggregateParamSum   AggregateParam = "sum"
)

// Valid indicates whether the value is a known member of the AggregateParam enum.
func (e AggregateParam) Valid() bool {
	switch e {
	case AggregateParamAvg:
		return true
	case AggregateParamCount:
		return true
	case AggregateParamMax:
		return true
	case AggregateParamMin:
		return true
	case AggregateParamSum:
		return true
	default:
		return false
	}
}

// Defines values for PrecisionParam.
const (
	PrecisionParamCentury      PrecisionParam = "century"
	PrecisionParamDay          PrecisionParam = "day"
	PrecisionParamDecade       PrecisionParam = "decade"
	PrecisionParamHour         PrecisionParam = "hour"
	PrecisionParamMicroseconds PrecisionParam = "microseconds"
	PrecisionParamMillennia    PrecisionParam = "millennia"
	PrecisionParamMilliseconds PrecisionParam = "milliseconds"
	PrecisionParamMinute       PrecisionParam = "minute"
	PrecisionParamMinute10     PrecisionParam = "minute10"
	PrecisionParamMinute15     PrecisionParam = "minute15"
	PrecisionParamMinute20     PrecisionParam = "minute20"
	PrecisionParamMinute30     PrecisionParam = "minute30"
	PrecisionParamMinute5      PrecisionParam = "minute5"
	PrecisionParamMonth        PrecisionParam = "month"
	PrecisionParamSecond       PrecisionParam = "second"
	PrecisionParamWeek         PrecisionParam = "week"
	PrecisionParamYear         PrecisionParam = "year"
)

// Valid indicates whether the value is a known member of the PrecisionParam enum.
func (e PrecisionParam) Valid() bool {
	switch e {
	case PrecisionParamCentury:
		return true
	case PrecisionParamDay:
		return true
	case PrecisionParamDecade:
		return true
	case PrecisionParamHour:
		return true
	case PrecisionParamMicroseconds:
		return true
	case PrecisionParamMillennia:
		return true
	case PrecisionParamMilliseconds:
		return true
	case PrecisionParamMinute:
		return true
	case PrecisionParamMinute10:
		return true
	case PrecisionParamMinute15:
		return true
	case PrecisionParamMinute20:
		return true
	case PrecisionParamMinute30:
		return true
	case PrecisionParamMinute5:
		return true
	case PrecisionParamMonth:
		return true
	case PrecisionParamSecond:
		return true
	case PrecisionParamWeek:
		return true
	case PrecisionParamYear:
		return true
	default:
		return false
	}
}

// Defines values for NewDatasetFormat.
const (
	NewDatasetFormatCsv  NewDatasetFormat = "csv"
	NewDatasetFormatIni  NewDatasetFormat = "ini"
	NewDatasetFormatJson NewDatasetFormat = "json"
	NewDatasetFormatMisc NewDatasetFormat = "misc"
	NewDatasetFormatToml NewDatasetFormat = "toml"
	NewDatasetFormatXml  NewDatasetFormat = "xml"
	NewDatasetFormatYaml NewDatasetFormat = "yaml"
)

// Valid indicates whether the value is a known member of the NewDatasetFormat enum.
func (e NewDatasetFormat) Valid() bool {
	switch e {
	case NewDatasetFormatCsv:
		return true
	case NewDatasetFormatIni:
		return true
	case NewDatasetFormatJson:
		return true
	case NewDatasetFormatMisc:
		return true
	case NewDatasetFormatToml:
		return true
	case NewDatasetFormatXml:
		return true
	case NewDatasetFormatYaml:
		return true
	default:
		return false
	}
}

// Defines values for NewPolicyAction.
const (
	NewPolicyActionCreate NewPolicyAction = "create"
	NewPolicyActionDelete NewPolicyAction = "delete"
	NewPolicyActionRead   NewPolicyAction = "read"
	NewPolicyActionUpdate NewPolicyAction = "update"
)

// Valid indicates whether the value is a known member of the NewPolicyAction enum.
func (e NewPolicyAction) Valid() bool {
	switch e {
	case NewPolicyActionCreate:
		return true
	case NewPolicyActionDelete:
		return true
	case NewPolicyActionRead:
		return true
	case NewPolicyActionUpdate:
		return true
	default:
		return false
	}
}

// Defines values for NewPolicyEffect.
const (
	NewPolicyEffectAllow NewPolicyEffect = "allow"
	NewPolicyEffectDeny  NewPolicyEffect = "deny"
)

// Valid indicates whether the value is a known member of the NewPolicyEffect enum.
func (e NewPolicyEffect) Valid() bool {
	switch e {
	case NewPolicyEffectAllow:
		return true
	case NewPolicyEffectDeny:
		return true
	default:
		return false
	}
}

// Defines values for NewProgramLanguage.
const (
	NewProgramLanguageTengo NewProgramLanguage = "tengo"
)

// Valid indicates whether the value is a known member of the NewProgramLanguage enum.
func (e NewProgramLanguage) Valid() bool {
	switch e {
	case NewProgramLanguageTengo:
		return true
	default:
		return false
	}
}

// Defines values for NewProgramState.
const (
	NewProgramStateActive   NewProgramState = "active"
	NewProgramStateFailed   NewProgramState = "failed"
	NewProgramStateInactive NewProgramState = "inactive"
)

// Valid indicates whether the value is a known member of the NewProgramState enum.
func (e NewProgramState) Valid() bool {
	switch e {
	case NewProgramStateActive:
		return true
	case NewProgramStateFailed:
		return true
	case NewProgramStateInactive:
		return true
	default:
		return false
	}
}

// Defines values for NewProgramType.
const (
	NewProgramTypeModule  NewProgramType = "module"
	NewProgramTypeRoutine NewProgramType = "routine"
	NewProgramTypeWebhook NewProgramType = "webhook"
)

// Valid indicates whether the value is a known member of the NewProgramType enum.
func (e NewProgramType) Valid() bool {
	switch e {
	case NewProgramTypeModule:
		return true
	case NewProgramTypeRoutine:
		return true
	case NewProgramTypeWebhook:
		return true
	default:
		return false
	}
}

// Defines values for UpdateDatasetFormat.
const (
	UpdateDatasetFormatCsv  UpdateDatasetFormat = "csv"
	UpdateDatasetFormatIni  UpdateDatasetFormat = "ini"
	UpdateDatasetFormatJson UpdateDatasetFormat = "json"
	UpdateDatasetFormatMisc UpdateDatasetFormat = "misc"
	UpdateDatasetFormatToml UpdateDatasetFormat = "toml"
	UpdateDatasetFormatXml  UpdateDatasetFormat = "xml"
	UpdateDatasetFormatYaml UpdateDatasetFormat = "yaml"
)

// Valid indicates whether the value is a known member of the UpdateDatasetFormat enum.
func (e UpdateDatasetFormat) Valid() bool {
	switch e {
	case UpdateDatasetFormatCsv:
		return true
	case UpdateDatasetFormatIni:
		return true
	case UpdateDatasetFormatJson:
		return true
	case UpdateDatasetFormatMisc:
		return true
	case UpdateDatasetFormatToml:
		return true
	case UpdateDatasetFormatXml:
		return true
	case UpdateDatasetFormatYaml:
		return true
	default:
		return false
	}
}

// Defines values for UpdatePolicyAction.
const (
	UpdatePolicyActionCreate UpdatePolicyAction = "create"
	UpdatePolicyActionDelete UpdatePolicyAction = "delete"
	UpdatePolicyActionRead   UpdatePolicyAction = "read"
	UpdatePolicyActionUpdate UpdatePolicyAction = "update"
)

// Valid indicates whether the value is a known member of the UpdatePolicyAction enum.
func (e UpdatePolicyAction) Valid() bool {
	switch e {
	case UpdatePolicyActionCreate:
		return true
	case UpdatePolicyActionDelete:
		return true
	case UpdatePolicyActionRead:
		return true
	case UpdatePolicyActionUpdate:
		return true
	default:
		return false
	}
}

// Defines values for UpdatePolicyEffect.
const (
	UpdatePolicyEffectAllow UpdatePolicyEffect = "allow"
	UpdatePolicyEffectDeny  UpdatePolicyEffect = "deny"
)

// Valid indicates whether the value is a known member of the UpdatePolicyEffect enum.
func (e UpdatePolicyEffect) Valid() bool {
	switch e {
	case UpdatePolicyEffectAllow:
		return true
	case UpdatePolicyEffectDeny:
		return true
	default:
		return false
	}
}

// Defines values for UpdateProgramLanguage.
const (
	UpdateProgramLanguageTengo UpdateProgramLanguage = "tengo"
)

// Valid indicates whether the value is a known member of the UpdateProgramLanguage enum.
func (e UpdateProgramLanguage) Valid() bool {
	switch e {
	case UpdateProgramLanguageTengo:
		return true
	default:
		return false
	}
}

// Defines values for UpdateProgramState.
const (
	UpdateProgramStateActive   UpdateProgramState = "active"
	UpdateProgramStateFailed   UpdateProgramState = "failed"
	UpdateProgramStateInactive UpdateProgramState = "inactive"
)

// Valid indicates whether the value is a known member of the UpdateProgramState enum.
func (e UpdateProgramState) Valid() bool {
	switch e {
	case UpdateProgramStateActive:
		return true
	case UpdateProgramStateFailed:
		return true
	case UpdateProgramStateInactive:
		return true
	default:
		return false
	}
}

// Defines values for UpdateProgramType.
const (
	UpdateProgramTypeModule  UpdateProgramType = "module"
	UpdateProgramTypeRoutine UpdateProgramType = "routine"
	UpdateProgramTypeWebhook UpdateProgramType = "webhook"
)

// Valid indicates whether the value is a known member of the UpdateProgramType enum.
func (e UpdateProgramType) Valid() bool {
	switch e {
	case UpdateProgramTypeModule:
		return true
	case UpdateProgramTypeRoutine:
		return true
	case UpdateProgramTypeWebhook:
		return true
	default:
		return false
	}
}

// Defines values for UpdateThingState.
const (
	UpdateThingStateActive   UpdateThingState = "active"
	UpdateThingStateArchived UpdateThingState = "archived"
	UpdateThingStateInactive UpdateThingState = "inactive"
	UpdateThingStatePassive  UpdateThingState = "passive"
)

// Valid indicates whether the value is a known member of the UpdateThingState enum.
func (e UpdateThingState) Valid() bool {
	switch e {
	case UpdateThingStateActive:
		return true
	case UpdateThingStateArchived:
		return true
	case UpdateThingStateInactive:
		return true
	case UpdateThingStatePassive:
		return true
	default:
		return false
	}
}

// Defines values for AddDatasetsJSONBodyFormat.
const (
	AddDatasetsJSONBodyFormatCsv  AddDatasetsJSONBodyFormat = "csv"
	AddDatasetsJSONBodyFormatIni  AddDatasetsJSONBodyFormat = "ini"
	AddDatasetsJSONBodyFormatJson AddDatasetsJSONBodyFormat = "json"
	AddDatasetsJSONBodyFormatMisc AddDatasetsJSONBodyFormat = "misc"
	AddDatasetsJSONBodyFormatToml AddDatasetsJSONBodyFormat = "toml"
	AddDatasetsJSONBodyFormatXml  AddDatasetsJSONBodyFormat = "xml"
	AddDatasetsJSONBodyFormatYaml AddDatasetsJSONBodyFormat = "yaml"
)

// Valid indicates whether the value is a known member of the AddDatasetsJSONBodyFormat enum.
func (e AddDatasetsJSONBodyFormat) Valid() bool {
	switch e {
	case AddDatasetsJSONBodyFormatCsv:
		return true
	case AddDatasetsJSONBodyFormatIni:
		return true
	case AddDatasetsJSONBodyFormatJson:
		return true
	case AddDatasetsJSONBodyFormatMisc:
		return true
	case AddDatasetsJSONBodyFormatToml:
		return true
	case AddDatasetsJSONBodyFormatXml:
		return true
	case AddDatasetsJSONBodyFormatYaml:
		return true
	default:
		return false
	}
}

// Defines values for UpdateDatasetByUuidJSONBodyFormat.
const (
	Csv  UpdateDatasetByUuidJSONBodyFormat = "csv"
	Ini  UpdateDatasetByUuidJSONBodyFormat = "ini"
	Json UpdateDatasetByUuidJSONBodyFormat = "json"
	Misc UpdateDatasetByUuidJSONBodyFormat = "misc"
	Toml UpdateDatasetByUuidJSONBodyFormat = "toml"
	Xml  UpdateDatasetByUuidJSONBodyFormat = "xml"
	Yaml UpdateDatasetByUuidJSONBodyFormat = "yaml"
)

// Valid indicates whether the value is a known member of the UpdateDatasetByUuidJSONBodyFormat enum.
func (e UpdateDatasetByUuidJSONBodyFormat) Valid() bool {
	switch e {
	case Csv:
		return true
	case Ini:
		return true
	case Json:
		return true
	case Misc:
		return true
	case Toml:
		return true
	case Xml:
		return true
	case Yaml:
		return true
	default:
		return false
	}
}

// Defines values for AddPolicyJSONBodyAction.
const (
	AddPolicyJSONBodyActionCreate AddPolicyJSONBodyAction = "create"
	AddPolicyJSONBodyActionDelete AddPolicyJSONBodyAction = "delete"
	AddPolicyJSONBodyActionRead   AddPolicyJSONBodyAction = "read"
	AddPolicyJSONBodyActionUpdate AddPolicyJSONBodyAction = "update"
)

// Valid indicates whether the value is a known member of the AddPolicyJSONBodyAction enum.
func (e AddPolicyJSONBodyAction) Valid() bool {
	switch e {
	case AddPolicyJSONBodyActionCreate:
		return true
	case AddPolicyJSONBodyActionDelete:
		return true
	case AddPolicyJSONBodyActionRead:
		return true
	case AddPolicyJSONBodyActionUpdate:
		return true
	default:
		return false
	}
}

// Defines values for AddPolicyJSONBodyEffect.
const (
	AddPolicyJSONBodyEffectAllow AddPolicyJSONBodyEffect = "allow"
	AddPolicyJSONBodyEffectDeny  AddPolicyJSONBodyEffect = "deny"
)

// Valid indicates whether the value is a known member of the AddPolicyJSONBodyEffect enum.
func (e AddPolicyJSONBodyEffect) Valid() bool {
	switch e {
	case AddPolicyJSONBodyEffectAllow:
		return true
	case AddPolicyJSONBodyEffectDeny:
		return true
	default:
		return false
	}
}

// Defines values for ExplainPolicyDecisionParamsAction.
const (
	ExplainPolicyDecisionParamsActionCreate ExplainPolicyDecisionParamsAction = "create"
	ExplainPolicyDecisionParamsActionDelete ExplainPolicyDecisionParamsAction = "delete"
	ExplainPolicyDecisionParamsActionRead   ExplainPolicyDecisionParamsAction = "read"
	ExplainPolicyDecisionParamsActionUpdate ExplainPolicyDecisionParamsAction = "update"
)

// Valid indicates whether the value is a known member of the ExplainPolicyDecisionParamsAction enum.
func (e ExplainPolicyDecisionParamsAction) Valid() bool {
	switch e {
	case ExplainPolicyDecisionParamsActionCreate:
		return true
	case ExplainPolicyDecisionParamsActionDelete:
		return true
	case ExplainPolicyDecisionParamsActionRead:
		return true
	case ExplainPolicyDecisionParamsActionUpdate:
		return true
	default:
		return false
	}
}

// Defines values for UpdatePolicyByUuidJSONBodyAction.
const (
	Create UpdatePolicyByUuidJSONBodyAction = "create"
	Delete UpdatePolicyByUuidJSONBodyAction = "delete"
	Read   UpdatePolicyByUuidJSONBodyAction = "read"
	Update UpdatePolicyByUuidJSONBodyAction = "update"
)

// Valid indicates whether the value is a known member of the UpdatePolicyByUuidJSONBodyAction enum.
func (e UpdatePolicyByUuidJSONBodyAction) Valid() bool {
	switch e {
	case Create:
		return true
	case Delete:
		return true
	case Read:
		return true
	case Update:
		return true
	default:
		return false
	}
}

// Defines values for UpdatePolicyByUuidJSONBodyEffect.
const (
	UpdatePolicyByUuidJSONBodyEffectAllow UpdatePolicyByUuidJSONBodyEffect = "allow"
	UpdatePolicyByUuidJSONBodyEffectDeny  UpdatePolicyByUuidJSONBodyEffect = "deny"
)

// Valid indicates whether the value is a known member of the UpdatePolicyByUuidJSONBodyEffect enum.
func (e UpdatePolicyByUuidJSONBodyEffect) Valid() bool {
	switch e {
	case UpdatePolicyByUuidJSONBodyEffectAllow:
		return true
	case UpdatePolicyByUuidJSONBodyEffectDeny:
		return true
	default:
		return false
	}
}

// Defines values for AddProgramJSONBodyLanguage.
const (
	AddProgramJSONBodyLanguageTengo AddProgramJSONBodyLanguage = "tengo"
)

// Valid indicates whether the value is a known member of the AddProgramJSONBodyLanguage enum.
func (e AddProgramJSONBodyLanguage) Valid() bool {
	switch e {
	case AddProgramJSONBodyLanguageTengo:
		return true
	default:
		return false
	}
}

// Defines values for AddProgramJSONBodyState.
const (
	AddProgramJSONBodyStateActive   AddProgramJSONBodyState = "active"
	AddProgramJSONBodyStateFailed   AddProgramJSONBodyState = "failed"
	AddProgramJSONBodyStateInactive AddProgramJSONBodyState = "inactive"
)

// Valid indicates whether the value is a known member of the AddProgramJSONBodyState enum.
func (e AddProgramJSONBodyState) Valid() bool {
	switch e {
	case AddProgramJSONBodyStateActive:
		return true
	case AddProgramJSONBodyStateFailed:
		return true
	case AddProgramJSONBodyStateInactive:
		return true
	default:
		return false
	}
}

// Defines values for AddProgramJSONBodyType.
const (
	AddProgramJSONBodyTypeModule  AddProgramJSONBodyType = "module"
	AddProgramJSONBodyTypeRoutine AddProgramJSONBodyType = "routine"
	AddProgramJSONBodyTypeWebhook AddProgramJSONBodyType = "webhook"
)

// Valid indicates whether the value is a known member of the AddProgramJSONBodyType enum.
func (e AddProgramJSONBodyType) Valid() bool {
	switch e {
	case AddProgramJSONBodyTypeModule:
		return true
	case AddProgramJSONBodyTypeRoutine:
		return true
	case AddProgramJSONBodyTypeWebhook:
		return true
	default:
		return false
	}
}

// Defines values for UpdateProgramByUuidJSONBodyLanguage.
const (
	Tengo UpdateProgramByUuidJSONBodyLanguage = "tengo"
)

// Valid indicates whether the value is a known member of the UpdateProgramByUuidJSONBodyLanguage enum.
func (e UpdateProgramByUuidJSONBodyLanguage) Valid() bool {
	switch e {
	case Tengo:
		return true
	default:
		return false
	}
}

// Defines values for UpdateProgramByUuidJSONBodyState.
const (
	UpdateProgramByUuidJSONBodyStateActive   UpdateProgramByUuidJSONBodyState = "active"
	UpdateProgramByUuidJSONBodyStateFailed   UpdateProgramByUuidJSONBodyState = "failed"
	UpdateProgramByUuidJSONBodyStateInactive UpdateProgramByUuidJSONBodyState = "inactive"
)

// Valid indicates whether the value is a known member of the UpdateProgramByUuidJSONBodyState enum.
func (e UpdateProgramByUuidJSONBodyState) Valid() bool {
	switch e {
	case UpdateProgramByUuidJSONBodyStateActive:
		return true
	case UpdateProgramByUuidJSONBodyStateFailed:
		return true
	case UpdateProgramByUuidJSONBodyStateInactive:
		return true
	default:
		return false
	}
}

// Defines values for UpdateProgramByUuidJSONBodyType.
const (
	Module  UpdateProgramByUuidJSONBodyType = "module"
	Routine UpdateProgramByUuidJSONBodyType = "routine"
	Webhook UpdateProgramByUuidJSONBodyType = "webhook"
)

// Valid indicates whether the value is a known member of the UpdateProgramByUuidJSONBodyType enum.
func (e UpdateProgramByUuidJSONBodyType) Valid() bool {
	switch e {
	case Module:
		return true
	case Routine:
		return true
	case Webhook:
		return true
	default:
		return false
	}
}

// Defines values for UpdateThingByUuidJSONBodyState.
const (
	UpdateThingByUuidJSONBodyStateActive   UpdateThingByUuidJSONBodyState = "active"
	UpdateThingByUuidJSONBodyStateArchived UpdateThingByUuidJSONBodyState = "archived"
	UpdateThingByUuidJSONBodyStateInactive UpdateThingByUuidJSONBodyState = "inactive"
	UpdateThingByUuidJSONBodyStatePassive  UpdateThingByUuidJSONBodyState = "passive"
)

// Valid indicates whether the value is a known member of the UpdateThingByUuidJSONBodyState enum.
func (e UpdateThingByUuidJSONBodyState) Valid() bool {
	switch e {
	case UpdateThingByUuidJSONBodyStateActive:
		return true
	case UpdateThingByUuidJSONBodyStateArchived:
		return true
	case UpdateThingByUuidJSONBodyStateInactive:
		return true
	case UpdateThingByUuidJSONBodyStatePassive:
		return true
	default:
		return false
	}
}

// Defines values for QueryTimeseriesForDataParamsPrecision.
const (
	QueryTimeseriesForDataParamsPrecisionCentury      QueryTimeseriesForDataParamsPrecision = "century"
	QueryTimeseriesForDataParamsPrecisionDay          QueryTimeseriesForDataParamsPrecision = "day"
	QueryTimeseriesForDataParamsPrecisionDecade       QueryTimeseriesForDataParamsPrecision = "decade"
	QueryTimeseriesForDataParamsPrecisionHour         QueryTimeseriesForDataParamsPrecision = "hour"
	QueryTimeseriesForDataParamsPrecisionMicroseconds QueryTimeseriesForDataParamsPrecision = "microseconds"
	QueryTimeseriesForDataParamsPrecisionMillennia    QueryTimeseriesForDataParamsPrecision = "millennia"
	QueryTimeseriesForDataParamsPrecisionMilliseconds QueryTimeseriesForDataParamsPrecision = "milliseconds"
	QueryTimeseriesForDataParamsPrecisionMinute       QueryTimeseriesForDataParamsPrecision = "minute"
	QueryTimeseriesForDataParamsPrecisionMinute10     QueryTimeseriesForDataParamsPrecision = "minute10"
	QueryTimeseriesForDataParamsPrecisionMinute15     QueryTimeseriesForDataParamsPrecision = "minute15"
	QueryTimeseriesForDataParamsPrecisionMinute20     QueryTimeseriesForDataParamsPrecision = "minute20"
	QueryTimeseriesForDataParamsPrecisionMinute30     QueryTimeseriesForDataParamsPrecision = "minute30"
	QueryTimeseriesForDataParamsPrecisionMinute5      QueryTimeseriesForDataParamsPrecision = "minute5"
	QueryTimeseriesForDataParamsPrecisionMonth        QueryTimeseriesForDataParamsPrecision = "month"
	QueryTimeseriesForDataParamsPrecisionSecond       QueryTimeseriesForDataParamsPrecision = "second"
	QueryTimeseriesForDataParamsPrecisionWeek         QueryTimeseriesForDataParamsPrecision = "week"
	QueryTimeseriesForDataParamsPrecisionYear         QueryTimeseriesForDataParamsPrecision = "year"
)

// Valid indicates whether the value is a known member of the QueryTimeseriesForDataParamsPrecision enum.
func (e QueryTimeseriesForDataParamsPrecision) Valid() bool {
	switch e {
	case QueryTimeseriesForDataParamsPrecisionCentury:
		return true
	case QueryTimeseriesForDataParamsPrecisionDay:
		return true
	case QueryTimeseriesForDataParamsPrecisionDecade:
		return true
	case QueryTimeseriesForDataParamsPrecisionHour:
		return true
	case QueryTimeseriesForDataParamsPrecisionMicroseconds:
		return true
	case QueryTimeseriesForDataParamsPrecisionMillennia:
		return true
	case QueryTimeseriesForDataParamsPrecisionMilliseconds:
		return true
	case QueryTimeseriesForDataParamsPrecisionMinute:
		return true
	case QueryTimeseriesForDataParamsPrecisionMinute10:
		return true
	case QueryTimeseriesForDataParamsPrecisionMinute15:
		return true
	case QueryTimeseriesForDataParamsPrecisionMinute20:
		return true
	case QueryTimeseriesForDataParamsPrecisionMinute30:
		return true
	case QueryTimeseriesForDataParamsPrecisionMinute5:
		return true
	case QueryTimeseriesForDataParamsPrecisionMonth:
		return true
	case QueryTimeseriesForDataParamsPrecisionSecond:
		return true
	case QueryTimeseriesForDataParamsPrecisionWeek:
		return true
	case QueryTimeseriesForDataParamsPrecisionYear:
		return true
	default:
		return false
	}
}

// Defines values for QueryTimeseriesForDataParamsAggregate.
const (
	QueryTimeseriesForDataParamsAggregateAvg   QueryTimeseriesForDataParamsAggregate = "avg"
	QueryTimeseriesForDataParamsAggregateCount QueryTimeseriesForDataParamsAggregate = "count"
	QueryTimeseriesForDataParamsAggregateMax   QueryTimeseriesForDataParamsAggregate = "max"
	QueryTimeseriesForDataParamsAggregateMin   QueryTimeseriesForDataParamsAggregate = "min"
	QueryTimeseriesForDataParamsAggregateSum   QueryTimeseriesForDataParamsAggregate = "sum"
)

// Valid indicates whether the value is a known member of the QueryTimeseriesForDataParamsAggregate enum.
func (e QueryTimeseriesForDataParamsAggregate) Valid() bool {
	switch e {
	case QueryTimeseriesForDataParamsAggregateAvg:
		return true
	case QueryTimeseriesForDataParamsAggregateCount:
		return true
	case QueryTimeseriesForDataParamsAggregateMax:
		return true
	case QueryTimeseriesForDataParamsAggregateMin:
		return true
	case QueryTimeseriesForDataParamsAggregateSum:
		return true
	default:
		return false
	}
}

// Defines values for FindTsdataByQueryParamsPrecision.
const (
	Century      FindTsdataByQueryParamsPrecision = "century"
	Day          FindTsdataByQueryParamsPrecision = "day"
	Decade       FindTsdataByQueryParamsPrecision = "decade"
	Hour         FindTsdataByQueryParamsPrecision = "hour"
	Microseconds FindTsdataByQueryParamsPrecision = "microseconds"
	Millennia    FindTsdataByQueryParamsPrecision = "millennia"
	Milliseconds FindTsdataByQueryParamsPrecision = "milliseconds"
	Minute       FindTsdataByQueryParamsPrecision = "minute"
	Minute10     FindTsdataByQueryParamsPrecision = "minute10"
	Minute15     FindTsdataByQueryParamsPrecision = "minute15"
	Minute20     FindTsdataByQueryParamsPrecision = "minute20"
	Minute30     FindTsdataByQueryParamsPrecision = "minute30"
	Minute5      FindTsdataByQueryParamsPrecision = "minute5"
	Month        FindTsdataByQueryParamsPrecision = "month"
	Second       FindTsdataByQueryParamsPrecision = "second"
	Week         FindTsdataByQueryParamsPrecision = "week"
	Year         FindTsdataByQueryParamsPrecision = "year"
)

// Valid indicates whether the value is a known member of the FindTsdataByQueryParamsPrecision enum.
func (e FindTsdataByQueryParamsPrecision) Valid() bool {
	switch e {
	case Century:
		return true
	case Day:
		return true
	case Decade:
		return true
	case Hour:
		return true
	case Microseconds:
		return true
	case Millennia:
		return true
	case Milliseconds:
		return true
	case Minute:
		return true
	case Minute10:
		return true
	case Minute15:
		return true
	case Minute20:
		return true
	case Minute30:
		return true
	case Minute5:
		return true
	case Month:
		return true
	case Second:
		return true
	case Week:
		return true
	case Year:
		return true
	default:
		return false
	}
}

// Defines values for FindTsdataByQueryParamsAggregate.
const (
	Avg   FindTsdataByQueryParamsAggregate = "avg"
	Count FindTsdataByQueryParamsAggregate = "count"
	Max   FindTsdataByQueryParamsAggregate = "max"
	Min   FindTsdataByQueryParamsAggregate = "min"
	Sum   FindTsdataByQueryParamsAggregate = "sum"
)

// Valid indicates whether the value is a known member of the FindTsdataByQueryParamsAggregate enum.
func (e FindTsdataByQueryParamsAggregate) Valid() bool {
	switch e {
	case Avg:
		return true
	case Count:
		return true
	case Max:
		return true
	case Min:
		return true
	case Sum:
		return true
	default:
		return false
	}
}

// Alert defines model for Alert.
type Alert struct {
	Created          time.Time     `json:"created"`
	Description      string        `json:"description"`
	Duplicate        int32         `json:"duplicate"`
	Environment      string        `json:"environment"`
	Event            string        `json:"event"`
	LastReceiveTime  *time.Time    `json:"last_receive_time"`
	Origin           string        `json:"origin"`
	PreviousSeverity AlertSeverity `json:"previous_severity"`
	Rawdata          []byte        `json:"rawdata"`
	Resource         string        `json:"resource"`
	Service          []string      `json:"service"`
	Severity         AlertSeverity `json:"severity"`
	Status           AlertStatus   `json:"status"`
	Tags             []string      `json:"tags"`
	Timeout          int32         `json:"timeout"`
	Uuid             string        `json:"uuid"`
	Value            string        `json:"value"`
}

// AlertSeverity defines model for AlertSeverity.
type AlertSeverity string

// AlertStatus defines model for AlertStatus.
type AlertStatus string

// AuthorizationDecision Explanation of the winning authorization decision for the current token.
type AuthorizationDecision struct {
	Access         bool                         `json:"access"`
	Action         AuthorizationDecisionAction  `json:"action"`
	Effect         *AuthorizationDecisionEffect `json:"effect,omitempty"`
	GroupUuid      *string                      `json:"group_uuid,omitempty"`
	MatchedPattern *string                      `json:"matched_pattern,omitempty"`
	PolicyUuid     *string                      `json:"policy_uuid,omitempty"`
	Priority       *int32                       `json:"priority,omitempty"`
	Resource       string                       `json:"resource"`
}

// AuthorizationDecisionAction defines model for AuthorizationDecision.Action.
type AuthorizationDecisionAction string

// AuthorizationDecisionEffect defines model for AuthorizationDecision.Effect.
type AuthorizationDecisionEffect string

// CodeRevision A stored revision of a program's source code.
type CodeRevision struct {
	Checksum string    `json:"checksum"`
	Created  time.Time `json:"created"`

	// CreatedBy User UUID
	CreatedBy string `json:"created_by"`

	// Revision The revision number
	Revision int        `json:"revision"`
	Signed   *time.Time `json:"signed"`

	// SignedBy User UUID
	SignedBy *string `json:"signed_by"`
}

// Dataset Dataset metadata stored by the API.
type Dataset struct {
	// Checksum The sha256 checksum of the content
	Checksum string `json:"checksum"`

	// Created Date-time when created, as defined by RFC 3339, section 5.6.
	Created time.Time `json:"created"`

	// CreatedBy User UUID reference.
	CreatedBy string `json:"created_by"`

	// Format File format of the data set.
	Format DatasetFormat `json:"format"`

	// Name Name of the resource. Does *not* have to be unique.
	Name string `json:"name"`

	// Size The size of the content in number of bytes.
	Size int64    `json:"size"`
	Tags []string `json:"tags"`

	// ThingUuid UUID reference to a Thing as a way to track data-sets to things.
	ThingUuid *string `json:"thing_uuid"`

	// Updated Date-time of last change, as defined by RFC 3339, section 5.6.
	Updated time.Time `json:"updated"`

	// UpdatedBy User UUID reference.
	UpdatedBy string `json:"updated_by"`

	// Uuid Unique identifier.
	Uuid string `json:"uuid"`
}

// DatasetFormat File format of the data set.
type DatasetFormat string

// DatasetUploadPart Metadata for one uploaded dataset part.
type DatasetUploadPart struct {
	ChecksumMD5 string    `json:"checksumMD5"`
	Created     time.Time `json:"created"`
	PartNumber  int       `json:"partNumber"`
	Size        int64     `json:"size"`
}

// DatasetUploadParts State of an in-progress multipart dataset upload.
type DatasetUploadParts struct {
	Parts    []DatasetUploadPart `json:"parts"`
	UploadId string              `json:"uploadId"`
}

// ErrorText Plain-text error response body.
type ErrorText = string

// Group Authorization group used to collect policies and assign them to users.
type Group struct {
	Name string `json:"name"`
	Uuid string `json:"uuid"`
}

// NewAlertReply The model returned when an Alert was created.
type NewAlertReply struct {
	Uuid string `json:"uuid"`
}

// Policy Access control policy that applies an effect to an action/resource pair.
type Policy struct {
	Action    PolicyAction `json:"action"`
	Effect    PolicyEffect `json:"effect"`
	GroupUuid string       `json:"group_uuid"`

	// Priority Lower numbers are evaluated first.
	Priority int32 `json:"priority"`

	// Resource Canonical resource path pattern without leading/trailing slash. Use `%` as a whole wildcard segment, for example `timeseries/%`.
	Resource string `json:"resource"`
	Uuid     string `json:"uuid"`
}

// PolicyAction defines model for Policy.Action.
type PolicyAction string

// PolicyEffect defines model for Policy.Effect.
type PolicyEffect string

// Program Program metadata for modules, routines, and webhooks.
type Program struct {
	// Deadline Ignored for Modules. An duration (in milliseconds) after which a Program (routine, webhook) shall terminate, to avoid long running programs.
	Deadline int             `json:"deadline"`
	Language ProgramLanguage `json:"language"`
	Name     string          `json:"name"`

	// Schedule Ignored for Modules and Webhooks. A CRON schedule on the typical [CRON format](https://en.wikipedia.org/wiki/Cron), yet with support for seconds.
	Schedule string `json:"schedule"`

	// State Administrative state of the program.
	State ProgramState `json:"state"`
	Tags  []string     `json:"tags"`

	// Type Routines are executed at an interval. Webhooks are called using the REST API. Modules are used by Routines and Webhooks to extend their functionality.
	Type ProgramType `json:"type"`
	Uuid string      `json:"uuid"`
}

// ProgramLanguage defines model for Program.Language.
type ProgramLanguage string

// ProgramState Administrative state of the program.
type ProgramState string

// ProgramType Routines are executed at an interval. Webhooks are called using the REST API. Modules are used by Routines and Webhooks to extend their functionality.
type ProgramType string

// Thing Thing metadata used to group datasets and time series around a logical object.
type Thing struct {
	// CreatedBy Reference to a User
	CreatedBy string     `json:"created_by"`
	Name      string     `json:"name"`
	State     ThingState `json:"state"`
	Tags      []string   `json:"tags"`
	Type      *string    `json:"type"`
	Uuid      string     `json:"uuid"`
}

// ThingState defines model for Thing.State.
type ThingState string

// Timeseries Time series metadata.
type Timeseries struct {
	CreatedBy  string   `json:"created_by"`
	LowerBound *float64 `json:"lower_bound"`
	Name       string   `json:"name"`
	SiUnit     string   `json:"si_unit"`
	Tags       []string `json:"tags"`
	ThingUuid  *string  `json:"thing_uuid"`
	UpperBound *float64 `json:"upper_bound"`
	Uuid       string   `json:"uuid"`
}

// Token Token metadata without the secret value.
type Token struct {
	Created time.Time `json:"created"`
	Name    string    `json:"name"`
	Uuid    string    `json:"uuid"`
}

// TokenWithSecret Token creation response including the one-time secret value.
type TokenWithSecret struct {
	Name   string `json:"name"`
	Secret string `json:"secret"`
	Uuid   string `json:"uuid"`
}

// TsResults Result for one requested time series in a multi-series query.
type TsResults struct {
	Data []TsRow `json:"data"`

	// Uuid Reference to a Timeseries
	Uuid string `json:"uuid"`
}

// TsRow One time series sample point.
type TsRow struct {
	// Ts Date-time when created, as defined by RFC 3339, section 5.6.
	Ts time.Time `json:"ts"`

	// V Any number
	V float32 `json:"v"`
}

// UploadResult Confirmation payload for successful part upload.
type UploadResult struct {
	Message string `json:"message"`
}

// User User account visible within a domain.
type User struct {
	// Groups Groups currently assigned to the user.
	Groups []Group `json:"groups"`
	Name   string  `json:"name"`
	Uuid   string  `json:"uuid"`
}

// AggregateParam defines model for aggregateParam.
type AggregateParam string

// EnvFilterParam defines model for envFilterParam.
type EnvFilterParam = string

// EventFilterParam defines model for eventFilterParam.
type EventFilterParam = string

// GreaterOrEqParam defines model for greaterOrEqParam.
type GreaterOrEqParam = float32

// IfNoneMatchParam defines model for ifNoneMatchParam.
type IfNoneMatchParam = string

// LessOrEqParam defines model for lessOrEqParam.
type LessOrEqParam = float32

// LimitParam defines model for limitParam.
type LimitParam = int64

// OffsetParam defines model for offsetParam.
type OffsetParam = int64

// OriginFilterParam defines model for originFilterParam.
type OriginFilterParam = string

// PrecisionParam defines model for precisionParam.
type PrecisionParam string

// RangeEndParam defines model for rangeEndParam.
type RangeEndParam = time.Time

// RangeStartParam defines model for rangeStartParam.
type RangeStartParam = time.Time

// ResourceFilterParam defines model for resourceFilterParam.
type ResourceFilterParam = string

// ServiceFilterParam defines model for serviceFilterParam.
type ServiceFilterParam = []string

// SeverityFilterParam defines model for severityFilterParam.
type SeverityFilterParam = AlertSeverity

// SeverityGeFilterParam defines model for severityGeFilterParam.
type SeverityGeFilterParam = AlertSeverity

// SeverityLeFilterParam defines model for severityLeFilterParam.
type SeverityLeFilterParam = AlertSeverity

// SiUnitParam defines model for siUnitParam.
type SiUnitParam = string

// StatusFilterParam defines model for statusFilterParam.
type StatusFilterParam = AlertStatus

// TagsFilterParam defines model for tagsFilterParam.
type TagsFilterParam = []string

// TimezoneParam defines model for timezoneParam.
type TimezoneParam = string

// UuidParam defines model for uuidParam.
type UuidParam = string

// NewAlert defines model for NewAlert.
type NewAlert struct {
	Description string `json:"description"`
	Environment string `json:"environment"`
	Event       string `json:"event"`
	Origin      string `json:"origin"`

	// Rawdata Base64 encoded raw data.
	Rawdata  *[]byte       `json:"rawdata,omitempty"`
	Resource string        `json:"resource"`
	Service  *[]string     `json:"service,omitempty"`
	Severity AlertSeverity `json:"severity"`
	Status   *AlertStatus  `json:"status,omitempty"`
	Tags     *[]string     `json:"tags,omitempty"`
	Timeout  *int32        `json:"timeout,omitempty"`
	Value    string        `json:"value"`
}

// NewDataset defines model for NewDataset.
type NewDataset struct {
	// Content Base64 encoded content of the dataset resource.
	Content *[]byte          `json:"content"`
	Format  NewDatasetFormat `json:"format"`
	Name    string           `json:"name"`

	// Tags An array of text labels (tags) for tracking and filtering purposes.
	Tags *[]string `json:"tags,omitempty"`

	// ThingUuid A reference to a Thing
	ThingUuid *string `json:"thing_uuid,omitempty"`
}

// NewDatasetFormat defines model for NewDataset.Format.
type NewDatasetFormat string

// NewGroup defines model for NewGroup.
type NewGroup struct {
	// Name Name of the group
	Name string `json:"name"`
}

// NewPolicy defines model for NewPolicy.
type NewPolicy struct {
	Action    NewPolicyAction `json:"action"`
	Effect    NewPolicyEffect `json:"effect"`
	GroupUuid string          `json:"group_uuid"`

	// Priority Lower numbers are evaluated first.
	Priority int `json:"priority"`

	// Resource Canonical resource path pattern without leading/trailing slash. Use `%` as a whole wildcard segment, for example `timeseries/%`.
	Resource string `json:"resource"`
}

// NewPolicyAction defines model for NewPolicy.Action.
type NewPolicyAction string

// NewPolicyEffect defines model for NewPolicy.Effect.
type NewPolicyEffect string

// NewProgram defines model for NewProgram.
type NewProgram struct {
	// Deadline Ignored for Modules. An duration (in milliseconds) after which a Program (routine, webhook) shall terminate, to avoid long running programs.
	Deadline int                `json:"deadline"`
	Language NewProgramLanguage `json:"language"`
	Name     string             `json:"name"`

	// Schedule Ignored for Modules and Webhooks. A CRON schedule on the typical [CRON format](https://en.wikipedia.org/wiki/Cron), yet with support for seconds.
	Schedule string          `json:"schedule"`
	State    NewProgramState `json:"state"`

	// Tags An array of text labels (tags) for tracking and filtering purposes.
	Tags *[]string `json:"tags,omitempty"`

	// Type Routines are executed at an interval. Webhooks are called using the REST API. Modules are used by Routines and Webhooks to extend their functionality.
	Type NewProgramType `json:"type"`
}

// NewProgramLanguage defines model for NewProgram.Language.
type NewProgramLanguage string

// NewProgramState defines model for NewProgram.State.
type NewProgramState string

// NewProgramType Routines are executed at an interval. Webhooks are called using the REST API. Modules are used by Routines and Webhooks to extend their functionality.
type NewProgramType string

// NewThing defines model for NewThing.
type NewThing struct {
	// Name Name of the thing
	Name string `json:"name"`

	// Tags An array of text labels (tags) for tracking and filtering purposes.
	Tags *[]string `json:"tags,omitempty"`

	// Type Thing type declaration
	Type *string `json:"type,omitempty"`
}

// NewTimeseries defines model for NewTimeseries.
type NewTimeseries struct {
	LowerBound *float64 `json:"lower_bound,omitempty"`

	// Name Name of the time series
	Name string `json:"name"`

	// SiUnit The SI unit assigned to this time series.
	SiUnit string    `json:"si_unit"`
	Tags   *[]string `json:"tags,omitempty"`

	// ThingUuid Optional reference to a thing
	ThingUuid  *string  `json:"thing_uuid,omitempty"`
	UpperBound *float64 `json:"upper_bound,omitempty"`
}

// NewToken defines model for NewToken.
type NewToken struct {
	// Name Name/label for the Token
	Name string `json:"name"`
}

// NewTsData defines model for NewTsData.
type NewTsData = []TsRow

// NewUser defines model for NewUser.
type NewUser struct {
	// Name Name of the user
	Name string `json:"name"`
}

// UpdateAlert defines model for UpdateAlert.
type UpdateAlert struct {
	Description *string `json:"description,omitempty"`
	Environment *string `json:"environment,omitempty"`
	Event       *string `json:"event,omitempty"`
	Origin      *string `json:"origin,omitempty"`

	// Rawdata Base64 encoded raw data.
	Rawdata  *[]byte        `json:"rawdata,omitempty"`
	Resource *string        `json:"resource,omitempty"`
	Service  *[]string      `json:"service,omitempty"`
	Severity *AlertSeverity `json:"severity,omitempty"`
	Status   *AlertStatus   `json:"status,omitempty"`
	Tags     *[]string      `json:"tags,omitempty"`
	Timeout  *int32         `json:"timeout,omitempty"`
	Value    *string        `json:"value,omitempty"`
}

// UpdateDataset The max allowed size of the complete request body is 1048576 bytes (1 MB). Larger content should be uploaded through the multipart dataset upload flow.
type UpdateDataset struct {
	// Content Base64 encoded content. Used for smaller uploads.
	Content *[]byte              `json:"content,omitempty"`
	Format  *UpdateDatasetFormat `json:"format,omitempty"`
	Name    *string              `json:"name,omitempty"`

	// Tags An array of text labels (tags) for tracking and filtering purposes.
	Tags *[]string `json:"tags,omitempty"`

	// ThingUuid A reference to a Thing
	ThingUuid *string `json:"thing_uuid,omitempty"`
}

// UpdateDatasetFormat defines model for UpdateDataset.Format.
type UpdateDatasetFormat string

// UpdateGroup defines model for UpdateGroup.
type UpdateGroup struct {
	Name string `json:"name"`
}

// UpdatePolicy defines model for UpdatePolicy.
type UpdatePolicy struct {
	Action    *UpdatePolicyAction `json:"action,omitempty"`
	Effect    *UpdatePolicyEffect `json:"effect,omitempty"`
	GroupUuid *string             `json:"group_uuid,omitempty"`
	Priority  *int                `json:"priority,omitempty"`
	Resource  *string             `json:"resource,omitempty"`
}

// UpdatePolicyAction defines model for UpdatePolicy.Action.
type UpdatePolicyAction string

// UpdatePolicyEffect defines model for UpdatePolicy.Effect.
type UpdatePolicyEffect string

// UpdateProgram defines model for UpdateProgram.
type UpdateProgram struct {
	// Deadline Ignored for Modules. An duration (in milliseconds) after which a Program (routine, webhook) shall terminate, to avoid long running programs.
	Deadline *int                   `json:"deadline,omitempty"`
	Language *UpdateProgramLanguage `json:"language,omitempty"`
	Name     *string                `json:"name,omitempty"`

	// Schedule Ignored for Modules and Webhooks. A CRON schedule on the typical [CRON format](https://en.wikipedia.org/wiki/Cron), yet with support for seconds.
	Schedule *string             `json:"schedule,omitempty"`
	State    *UpdateProgramState `json:"state,omitempty"`

	// Tags An array of text labels (tags) for tracking and filtering purposes.
	Tags *[]string `json:"tags,omitempty"`

	// Type Routines are executed at an interval. Webhooks are called using the REST API. Modules are used by Routines and Webhooks to extend their functionality.
	Type *UpdateProgramType `json:"type,omitempty"`
}

// UpdateProgramLanguage defines model for UpdateProgram.Language.
type UpdateProgramLanguage string

// UpdateProgramState defines model for UpdateProgram.State.
type UpdateProgramState string

// UpdateProgramType Routines are executed at an interval. Webhooks are called using the REST API. Modules are used by Routines and Webhooks to extend their functionality.
type UpdateProgramType string

// UpdateRequestRate defines model for UpdateRequestRate.
type UpdateRequestRate struct {
	Rate *float32 `json:"rate,omitempty"`
}

// UpdateThing defines model for UpdateThing.
type UpdateThing struct {
	// Name The name of the Thing.
	Name *string `json:"name,omitempty"`

	// State The state of the thing.
	State *UpdateThingState `json:"state,omitempty"`

	// Tags An array of text labels (tags) for tracking and filtering purposes.
	Tags *[]string `json:"tags,omitempty"`

	// Type A text label to organize Things into different types.
	Type *string `json:"type,omitempty"`
}

// UpdateThingState The state of the thing.
type UpdateThingState string

// UpdateTimeseries defines model for UpdateTimeseries.
type UpdateTimeseries struct {
	// LowerBound An optional lower bound at which values are accepted and stored. Values *less* than this will be rejected.
	LowerBound *float64 `json:"lower_bound,omitempty"`

	// Name Name of the time-series.
	Name *string `json:"name,omitempty"`

	// SiUnit SI unit.
	SiUnit *string `json:"si_unit,omitempty"`

	// Tags An array of text labels (tags) for tracking and filtering purposes.
	Tags *[]string `json:"tags,omitempty"`

	// ThingUuid Optional reference to a Thing.
	ThingUuid *string `json:"thing_uuid,omitempty"`

	// UpperBound An optional upper bound at which values are accepted and stored. Values *greater* than this will be rejected.
	UpperBound *float64 `json:"upper_bound,omitempty"`
}

// UpdateUser defines model for UpdateUser.
type UpdateUser struct {
	// Groups Set the user groups. This parameter is incompatible with `groups_add` and `groups_remove`.
	Groups *[]string `json:"groups,omitempty"`

	// GroupsAdd Add the user to these groups. This parameter is incompatible with `groups`.
	GroupsAdd *[]string `json:"groups_add,omitempty"`

	// GroupsRemove Remove the user from these groups. This parameter is incompatible with `groups`.
	GroupsRemove *[]string `json:"groups_remove,omitempty"`
	Name         *string   `json:"name,omitempty"`
}

// FindAlertsParams defines parameters for FindAlerts.
type FindAlertsParams struct {
	// Offset The number of items to skip before starting to collect the result set.
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit The numbers of items to return.
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// Resource Alert resource
	Resource *ResourceFilterParam `form:"resource,omitempty" json:"resource,omitempty"`

	// Environment Alert environment
	Environment *EnvFilterParam `form:"environment,omitempty" json:"environment,omitempty"`

	// Event Alert event
	Event *EventFilterParam `form:"event,omitempty" json:"event,omitempty"`

	// Origin Alert origin
	Origin *OriginFilterParam `form:"origin,omitempty" json:"origin,omitempty"`

	// Status Alert status
	Status *StatusFilterParam `form:"status,omitempty" json:"status,omitempty"`

	// SeverityLe Alert severity LessOrEqual to
	SeverityLe *SeverityLeFilterParam `form:"severity_le,omitempty" json:"severity_le,omitempty"`

	// SeverityGe Alert severity GreaterOrEqual to
	SeverityGe *SeverityGeFilterParam `form:"severity_ge,omitempty" json:"severity_ge,omitempty"`

	// Severity Alert severity
	Severity *SeverityFilterParam `form:"severity,omitempty" json:"severity,omitempty"`

	// Tags Array of tags to match on. All listed tags must match for a result to be returned.
	Tags *TagsFilterParam `form:"tags,omitempty" json:"tags,omitempty"`

	// Service Array of services to match on
	Service *ServiceFilterParam `form:"service,omitempty" json:"service,omitempty"`
}

// CreateAlertJSONBody defines parameters for CreateAlert.
type CreateAlertJSONBody struct {
	Description string `json:"description"`
	Environment string `json:"environment"`
	Event       string `json:"event"`
	Origin      string `json:"origin"`

	// Rawdata Base64 encoded raw data.
	Rawdata  *[]byte       `json:"rawdata,omitempty"`
	Resource string        `json:"resource"`
	Service  *[]string     `json:"service,omitempty"`
	Severity AlertSeverity `json:"severity"`
	Status   *AlertStatus  `json:"status,omitempty"`
	Tags     *[]string     `json:"tags,omitempty"`
	Timeout  *int32        `json:"timeout,omitempty"`
	Value    string        `json:"value"`
}

// UpdateAlertByUuidJSONBody defines parameters for UpdateAlertByUuid.
type UpdateAlertByUuidJSONBody struct {
	Description *string `json:"description,omitempty"`
	Environment *string `json:"environment,omitempty"`
	Event       *string `json:"event,omitempty"`
	Origin      *string `json:"origin,omitempty"`

	// Rawdata Base64 encoded raw data.
	Rawdata  *[]byte        `json:"rawdata,omitempty"`
	Resource *string        `json:"resource,omitempty"`
	Service  *[]string      `json:"service,omitempty"`
	Severity *AlertSeverity `json:"severity,omitempty"`
	Status   *AlertStatus   `json:"status,omitempty"`
	Tags     *[]string      `json:"tags,omitempty"`
	Timeout  *int32         `json:"timeout,omitempty"`
	Value    *string        `json:"value,omitempty"`
}

// FindDatasetsParams defines parameters for FindDatasets.
type FindDatasetsParams struct {
	// Offset The number of items to skip before starting to collect the result set.
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit The numbers of items to return.
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// Tags Array of tags to match on. All listed tags must match for a result to be returned.
	Tags *TagsFilterParam `form:"tags,omitempty" json:"tags,omitempty"`
}

// AddDatasetsJSONBody defines parameters for AddDatasets.
type AddDatasetsJSONBody struct {
	// Content Base64 encoded content of the dataset resource.
	Content *[]byte                   `json:"content"`
	Format  AddDatasetsJSONBodyFormat `json:"format"`
	Name    string                    `json:"name"`

	// Tags An array of text labels (tags) for tracking and filtering purposes.
	Tags *[]string `json:"tags,omitempty"`

	// ThingUuid A reference to a Thing
	ThingUuid *string `json:"thing_uuid,omitempty"`
}

// AddDatasetsJSONBodyFormat defines parameters for AddDatasets.
type AddDatasetsJSONBodyFormat string

// UpdateDatasetByUuidJSONBody defines parameters for UpdateDatasetByUuid.
type UpdateDatasetByUuidJSONBody struct {
	// Content Base64 encoded content. Used for smaller uploads.
	Content *[]byte                            `json:"content,omitempty"`
	Format  *UpdateDatasetByUuidJSONBodyFormat `json:"format,omitempty"`
	Name    *string                            `json:"name,omitempty"`

	// Tags An array of text labels (tags) for tracking and filtering purposes.
	Tags *[]string `json:"tags,omitempty"`

	// ThingUuid A reference to a Thing
	ThingUuid *string `json:"thing_uuid,omitempty"`
}

// UpdateDatasetByUuidJSONBodyFormat defines parameters for UpdateDatasetByUuid.
type UpdateDatasetByUuidJSONBodyFormat string

// AssembleDatasetPartsByKeyParams defines parameters for AssembleDatasetPartsByKey.
type AssembleDatasetPartsByKeyParams struct {
	UploadId   string `form:"uploadId" json:"uploadId"`
	ContentMD5 string `json:"Content-MD5"`
}

// ListDatasetPartsByKeyParams defines parameters for ListDatasetPartsByKey.
type ListDatasetPartsByKeyParams struct {
	UploadId string `form:"uploadId" json:"uploadId"`
}

// UploadDatasetContentByKeyParams defines parameters for UploadDatasetContentByKey.
type UploadDatasetContentByKeyParams struct {
	PartNumber int    `form:"partNumber" json:"partNumber"`
	UploadId   string `form:"uploadId" json:"uploadId"`
	ContentMD5 string `json:"Content-MD5"`
}

// GetRawDatasetByUuidParams defines parameters for GetRawDatasetByUuid.
type GetRawDatasetByUuidParams struct {
	// IfNoneMatch The server compares the client's ETag (sent with If-None-Match) with
	// the ETag for its current version of the resource, and if both values
	// match (that is, the resource has not changed), the server sends back
	// a 304 Not Modified status, without a body, which tells the client
	// that the cached version of the response is still good to use (fresh).
	IfNoneMatch *IfNoneMatchParam `json:"If-None-Match,omitempty"`
}

// DeleteDatasetUploadByKeyParams defines parameters for DeleteDatasetUploadByKey.
type DeleteDatasetUploadByKeyParams struct {
	UploadId string `form:"uploadId" json:"uploadId"`
}

// FindGroupsParams defines parameters for FindGroups.
type FindGroupsParams struct {
	// Limit The numbers of items to return.
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset The number of items to skip before starting to collect the result set.
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`
}

// AddGroupJSONBody defines parameters for AddGroup.
type AddGroupJSONBody struct {
	// Name Name of the group
	Name string `json:"name"`
}

// UpdateGroupByUuidJSONBody defines parameters for UpdateGroupByUuid.
type UpdateGroupByUuidJSONBody struct {
	Name string `json:"name"`
}

// FindPoliciesParams defines parameters for FindPolicies.
type FindPoliciesParams struct {
	// Offset The number of items to skip before starting to collect the result set.
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit The numbers of items to return.
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// GroupUuids Group(s) to filter on
	GroupUuids *[]string `form:"group_uuids,omitempty" json:"group_uuids,omitempty"`
}

// AddPolicyJSONBody defines parameters for AddPolicy.
type AddPolicyJSONBody struct {
	Action    AddPolicyJSONBodyAction `json:"action"`
	Effect    AddPolicyJSONBodyEffect `json:"effect"`
	GroupUuid string                  `json:"group_uuid"`

	// Priority Lower numbers are evaluated first.
	Priority int `json:"priority"`

	// Resource Canonical resource path pattern without leading/trailing slash. Use `%` as a whole wildcard segment, for example `timeseries/%`.
	Resource string `json:"resource"`
}

// AddPolicyJSONBodyAction defines parameters for AddPolicy.
type AddPolicyJSONBodyAction string

// AddPolicyJSONBodyEffect defines parameters for AddPolicy.
type AddPolicyJSONBodyEffect string

// ExplainPolicyDecisionParams defines parameters for ExplainPolicyDecision.
type ExplainPolicyDecisionParams struct {
	// Action Action to evaluate.
	Action ExplainPolicyDecisionParamsAction `form:"action" json:"action"`

	// Resource Canonical resource path to evaluate, for example `timeseries/123/data`.
	Resource string `form:"resource" json:"resource"`
}

// ExplainPolicyDecisionParamsAction defines parameters for ExplainPolicyDecision.
type ExplainPolicyDecisionParamsAction string

// UpdatePolicyByUuidJSONBody defines parameters for UpdatePolicyByUuid.
type UpdatePolicyByUuidJSONBody struct {
	Action    *UpdatePolicyByUuidJSONBodyAction `json:"action,omitempty"`
	Effect    *UpdatePolicyByUuidJSONBodyEffect `json:"effect,omitempty"`
	GroupUuid *string                           `json:"group_uuid,omitempty"`
	Priority  *int                              `json:"priority,omitempty"`
	Resource  *string                           `json:"resource,omitempty"`
}

// UpdatePolicyByUuidJSONBodyAction defines parameters for UpdatePolicyByUuid.
type UpdatePolicyByUuidJSONBodyAction string

// UpdatePolicyByUuidJSONBodyEffect defines parameters for UpdatePolicyByUuid.
type UpdatePolicyByUuidJSONBodyEffect string

// FindProgramsParams defines parameters for FindPrograms.
type FindProgramsParams struct {
	// Offset The number of items to skip before starting to collect the result set.
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit The numbers of items to return.
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// Tags Array of tags to match on. All listed tags must match for a result to be returned.
	Tags *TagsFilterParam `form:"tags,omitempty" json:"tags,omitempty"`
}

// AddProgramJSONBody defines parameters for AddProgram.
type AddProgramJSONBody struct {
	// Deadline Ignored for Modules. An duration (in milliseconds) after which a Program (routine, webhook) shall terminate, to avoid long running programs.
	Deadline int                        `json:"deadline"`
	Language AddProgramJSONBodyLanguage `json:"language"`
	Name     string                     `json:"name"`

	// Schedule Ignored for Modules and Webhooks. A CRON schedule on the typical [CRON format](https://en.wikipedia.org/wiki/Cron), yet with support for seconds.
	Schedule string                  `json:"schedule"`
	State    AddProgramJSONBodyState `json:"state"`

	// Tags An array of text labels (tags) for tracking and filtering purposes.
	Tags *[]string `json:"tags,omitempty"`

	// Type Routines are executed at an interval. Webhooks are called using the REST API. Modules are used by Routines and Webhooks to extend their functionality.
	Type AddProgramJSONBodyType `json:"type"`
}

// AddProgramJSONBodyLanguage defines parameters for AddProgram.
type AddProgramJSONBodyLanguage string

// AddProgramJSONBodyState defines parameters for AddProgram.
type AddProgramJSONBodyState string

// AddProgramJSONBodyType defines parameters for AddProgram.
type AddProgramJSONBodyType string

// UpdateProgramByUuidJSONBody defines parameters for UpdateProgramByUuid.
type UpdateProgramByUuidJSONBody struct {
	// Deadline Ignored for Modules. An duration (in milliseconds) after which a Program (routine, webhook) shall terminate, to avoid long running programs.
	Deadline *int                                 `json:"deadline,omitempty"`
	Language *UpdateProgramByUuidJSONBodyLanguage `json:"language,omitempty"`
	Name     *string                              `json:"name,omitempty"`

	// Schedule Ignored for Modules and Webhooks. A CRON schedule on the typical [CRON format](https://en.wikipedia.org/wiki/Cron), yet with support for seconds.
	Schedule *string                           `json:"schedule,omitempty"`
	State    *UpdateProgramByUuidJSONBodyState `json:"state,omitempty"`

	// Tags An array of text labels (tags) for tracking and filtering purposes.
	Tags *[]string `json:"tags,omitempty"`

	// Type Routines are executed at an interval. Webhooks are called using the REST API. Modules are used by Routines and Webhooks to extend their functionality.
	Type *UpdateProgramByUuidJSONBodyType `json:"type,omitempty"`
}

// UpdateProgramByUuidJSONBodyLanguage defines parameters for UpdateProgramByUuid.
type UpdateProgramByUuidJSONBodyLanguage string

// UpdateProgramByUuidJSONBodyState defines parameters for UpdateProgramByUuid.
type UpdateProgramByUuidJSONBodyState string

// UpdateProgramByUuidJSONBodyType defines parameters for UpdateProgramByUuid.
type UpdateProgramByUuidJSONBodyType string

// GetProgramCodeRevisionsDiffParams defines parameters for GetProgramCodeRevisionsDiff.
type GetProgramCodeRevisionsDiffParams struct {
	// RevA Revision A
	RevA int `form:"rev_a" json:"rev_a"`

	// RevB Revision B
	RevB int `form:"rev_b" json:"rev_b"`
}

// FindThingsParams defines parameters for FindThings.
type FindThingsParams struct {
	// Limit The numbers of items to return.
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset The number of items to skip before starting to collect the result set.
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`

	// Tags Array of tags to match on. All listed tags must match for a result to be returned.
	Tags *TagsFilterParam `form:"tags,omitempty" json:"tags,omitempty"`
}

// AddThingJSONBody defines parameters for AddThing.
type AddThingJSONBody struct {
	// Name Name of the thing
	Name string `json:"name"`

	// Tags An array of text labels (tags) for tracking and filtering purposes.
	Tags *[]string `json:"tags,omitempty"`

	// Type Thing type declaration
	Type *string `json:"type,omitempty"`
}

// UpdateThingByUuidJSONBody defines parameters for UpdateThingByUuid.
type UpdateThingByUuidJSONBody struct {
	// Name The name of the Thing.
	Name *string `json:"name,omitempty"`

	// State The state of the thing.
	State *UpdateThingByUuidJSONBodyState `json:"state,omitempty"`

	// Tags An array of text labels (tags) for tracking and filtering purposes.
	Tags *[]string `json:"tags,omitempty"`

	// Type A text label to organize Things into different types.
	Type *string `json:"type,omitempty"`
}

// UpdateThingByUuidJSONBodyState defines parameters for UpdateThingByUuid.
type UpdateThingByUuidJSONBodyState string

// FindTimeSeriesParams defines parameters for FindTimeSeries.
type FindTimeSeriesParams struct {
	// Limit The numbers of items to return.
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset The number of items to skip before starting to collect the result set.
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`

	// Tags Array of tags to match on. All listed tags must match for a result to be returned.
	Tags *TagsFilterParam `form:"tags,omitempty" json:"tags,omitempty"`
}

// AddTimeSeriesJSONBody defines parameters for AddTimeSeries.
type AddTimeSeriesJSONBody struct {
	LowerBound *float64 `json:"lower_bound,omitempty"`

	// Name Name of the time series
	Name string `json:"name"`

	// SiUnit The SI unit assigned to this time series.
	SiUnit string    `json:"si_unit"`
	Tags   *[]string `json:"tags,omitempty"`

	// ThingUuid Optional reference to a thing
	ThingUuid  *string  `json:"thing_uuid,omitempty"`
	UpperBound *float64 `json:"upper_bound,omitempty"`
}

// UpdateTimeseriesByUuidJSONBody defines parameters for UpdateTimeseriesByUuid.
type UpdateTimeseriesByUuidJSONBody struct {
	// LowerBound An optional lower bound at which values are accepted and stored. Values *less* than this will be rejected.
	LowerBound *float64 `json:"lower_bound,omitempty"`

	// Name Name of the time-series.
	Name *string `json:"name,omitempty"`

	// SiUnit SI unit.
	SiUnit *string `json:"si_unit,omitempty"`

	// Tags An array of text labels (tags) for tracking and filtering purposes.
	Tags *[]string `json:"tags,omitempty"`

	// ThingUuid Optional reference to a Thing.
	ThingUuid *string `json:"thing_uuid,omitempty"`

	// UpperBound An optional upper bound at which values are accepted and stored. Values *greater* than this will be rejected.
	UpperBound *float64 `json:"upper_bound,omitempty"`
}

// DeleteDataFromTimeSeriesParams defines parameters for DeleteDataFromTimeSeries.
type DeleteDataFromTimeSeriesParams struct {
	// Start Start (>=) of time period. The period (start to end) can **not** exceed 1 year.
	Start RangeStartParam `form:"start" json:"start"`

	// End End (<=) of time period. The period (start to end) can **not** exceed 1 year.
	End RangeEndParam `form:"end" json:"end"`

	// Ge Value should be greater or equal to (>=) this.
	Ge *GreaterOrEqParam `form:"ge,omitempty" json:"ge,omitempty"`

	// Le Value should be less or equal to (<=) this.
	Le *LessOrEqParam `form:"le,omitempty" json:"le,omitempty"`
}

// QueryTimeseriesForDataParams defines parameters for QueryTimeseriesForData.
type QueryTimeseriesForDataParams struct {
	// Start Start (>=) of time period. The period (start to end) can **not** exceed 1 year.
	Start RangeStartParam `form:"start" json:"start"`

	// End End (<=) of time period. The period (start to end) can **not** exceed 1 year.
	End RangeEndParam `form:"end" json:"end"`

	// Unit The SI unit of the result. A cast will occur if the base unit differes.
	Unit *SiUnitParam `form:"unit,omitempty" json:"unit,omitempty"`

	// Ge Value should be greater or equal to (>=) this.
	Ge *GreaterOrEqParam `form:"ge,omitempty" json:"ge,omitempty"`

	// Le Value should be less or equal to (<=) this.
	Le *LessOrEqParam `form:"le,omitempty" json:"le,omitempty"`

	// Precision Truncate all timestamps and perform aggregate operations on the grouping.
	Precision *QueryTimeseriesForDataParamsPrecision `form:"precision,omitempty" json:"precision,omitempty"`

	// Aggregate When using `precision`. Select this aggregate function instead of the default `avg` when computing the result. Does nothing when `precision` is not set.
	Aggregate *QueryTimeseriesForDataParamsAggregate `form:"aggregate,omitempty" json:"aggregate,omitempty"`

	// Timezone Act as this time zone when grouping or formatting timestamps. Defaults to `UTC`.
	Timezone *TimezoneParam `form:"timezone,omitempty" json:"timezone,omitempty"`
}

// QueryTimeseriesForDataParamsPrecision defines parameters for QueryTimeseriesForData.
type QueryTimeseriesForDataParamsPrecision string

// QueryTimeseriesForDataParamsAggregate defines parameters for QueryTimeseriesForData.
type QueryTimeseriesForDataParamsAggregate string

// AddDataToTimeseriesJSONBody defines parameters for AddDataToTimeseries.
type AddDataToTimeseriesJSONBody = []TsRow

// AddDataToTimeseriesParams defines parameters for AddDataToTimeseries.
type AddDataToTimeseriesParams struct {
	// Unit The SI unit of the result. A cast will occur if the base unit differes.
	Unit *SiUnitParam `form:"unit,omitempty" json:"unit,omitempty"`
}

// FindTsdataByQueryParams defines parameters for FindTsdataByQuery.
type FindTsdataByQueryParams struct {
	// Uuids A series of timeseries UUIDs to search for
	Uuids []string `form:"uuids" json:"uuids"`

	// Start Start (>=) of time period. The period (start to end) can **not** exceed 1 year.
	Start RangeStartParam `form:"start" json:"start"`

	// End End (<=) of time period. The period (start to end) can **not** exceed 1 year.
	End RangeEndParam `form:"end" json:"end"`

	// Ge Value should be greater or equal to (>=) this.
	Ge *GreaterOrEqParam `form:"ge,omitempty" json:"ge,omitempty"`

	// Le Value should be less or equal to (<=) this.
	Le *LessOrEqParam `form:"le,omitempty" json:"le,omitempty"`

	// Precision Truncate all timestamps and perform aggregate operations on the grouping.
	Precision *FindTsdataByQueryParamsPrecision `form:"precision,omitempty" json:"precision,omitempty"`

	// Aggregate When using `precision`. Select this aggregate function instead of the default `avg` when computing the result. Does nothing when `precision` is not set.
	Aggregate *FindTsdataByQueryParamsAggregate `form:"aggregate,omitempty" json:"aggregate,omitempty"`

	// Timezone Act as this time zone when grouping or formatting timestamps. Defaults to `UTC`.
	Timezone *TimezoneParam `form:"timezone,omitempty" json:"timezone,omitempty"`
}

// FindTsdataByQueryParamsPrecision defines parameters for FindTsdataByQuery.
type FindTsdataByQueryParamsPrecision string

// FindTsdataByQueryParamsAggregate defines parameters for FindTsdataByQuery.
type FindTsdataByQueryParamsAggregate string

// FindUsersParams defines parameters for FindUsers.
type FindUsersParams struct {
	// Limit The numbers of items to return.
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset The number of items to skip before starting to collect the result set.
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`
}

// AddUserJSONBody defines parameters for AddUser.
type AddUserJSONBody struct {
	// Name Name of the user
	Name string `json:"name"`
}

// UpdateUserByUuidJSONBody defines parameters for UpdateUserByUuid.
type UpdateUserByUuidJSONBody struct {
	// Groups Set the user groups. This parameter is incompatible with `groups_add` and `groups_remove`.
	Groups *[]string `json:"groups,omitempty"`

	// GroupsAdd Add the user to these groups. This parameter is incompatible with `groups`.
	GroupsAdd *[]string `json:"groups_add,omitempty"`

	// GroupsRemove Remove the user from these groups. This parameter is incompatible with `groups`.
	GroupsRemove *[]string `json:"groups_remove,omitempty"`
	Name         *string   `json:"name,omitempty"`
}

// SetRequestRateForUserJSONBody defines parameters for SetRequestRateForUser.
type SetRequestRateForUserJSONBody struct {
	Rate *float32 `json:"rate,omitempty"`
}

// AddNewTokenToUserJSONBody defines parameters for AddNewTokenToUser.
type AddNewTokenToUserJSONBody struct {
	// Name Name/label for the Token
	Name string `json:"name"`
}

// CreateAlertJSONRequestBody defines body for CreateAlert for application/json ContentType.
type CreateAlertJSONRequestBody CreateAlertJSONBody

// UpdateAlertByUuidJSONRequestBody defines body for UpdateAlertByUuid for application/json ContentType.
type UpdateAlertByUuidJSONRequestBody UpdateAlertByUuidJSONBody

// AddDatasetsJSONRequestBody defines body for AddDatasets for application/json ContentType.
type AddDatasetsJSONRequestBody AddDatasetsJSONBody

// UpdateDatasetByUuidJSONRequestBody defines body for UpdateDatasetByUuid for application/json ContentType.
type UpdateDatasetByUuidJSONRequestBody UpdateDatasetByUuidJSONBody

// AddGroupJSONRequestBody defines body for AddGroup for application/json ContentType.
type AddGroupJSONRequestBody AddGroupJSONBody

// UpdateGroupByUuidJSONRequestBody defines body for UpdateGroupByUuid for application/json ContentType.
type UpdateGroupByUuidJSONRequestBody UpdateGroupByUuidJSONBody

// AddPolicyJSONRequestBody defines body for AddPolicy for application/json ContentType.
type AddPolicyJSONRequestBody AddPolicyJSONBody

// UpdatePolicyByUuidJSONRequestBody defines body for UpdatePolicyByUuid for application/json ContentType.
type UpdatePolicyByUuidJSONRequestBody UpdatePolicyByUuidJSONBody

// AddProgramJSONRequestBody defines body for AddProgram for application/json ContentType.
type AddProgramJSONRequestBody AddProgramJSONBody

// UpdateProgramByUuidJSONRequestBody defines body for UpdateProgramByUuid for application/json ContentType.
type UpdateProgramByUuidJSONRequestBody UpdateProgramByUuidJSONBody

// AddThingJSONRequestBody defines body for AddThing for application/json ContentType.
type AddThingJSONRequestBody AddThingJSONBody

// UpdateThingByUuidJSONRequestBody defines body for UpdateThingByUuid for application/json ContentType.
type UpdateThingByUuidJSONRequestBody UpdateThingByUuidJSONBody

// AddTimeSeriesJSONRequestBody defines body for AddTimeSeries for application/json ContentType.
type AddTimeSeriesJSONRequestBody AddTimeSeriesJSONBody

// UpdateTimeseriesByUuidJSONRequestBody defines body for UpdateTimeseriesByUuid for application/json ContentType.
type UpdateTimeseriesByUuidJSONRequestBody UpdateTimeseriesByUuidJSONBody

// AddDataToTimeseriesJSONRequestBody defines body for AddDataToTimeseries for application/json ContentType.
type AddDataToTimeseriesJSONRequestBody = AddDataToTimeseriesJSONBody

// AddUserJSONRequestBody defines body for AddUser for application/json ContentType.
type AddUserJSONRequestBody AddUserJSONBody

// UpdateUserByUuidJSONRequestBody defines body for UpdateUserByUuid for application/json ContentType.
type UpdateUserByUuidJSONRequestBody UpdateUserByUuidJSONBody

// SetRequestRateForUserJSONRequestBody defines body for SetRequestRateForUser for application/json ContentType.
type SetRequestRateForUserJSONRequestBody SetRequestRateForUserJSONBody

// AddNewTokenToUserJSONRequestBody defines body for AddNewTokenToUser for application/json ContentType.
type AddNewTokenToUserJSONRequestBody AddNewTokenToUserJSONBody
