# syntax=docker/dockerfile:1
FROM golang:1.25 AS builder
WORKDIR /src
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/aapije ./cmd/aapije

FROM alpine:3.22
RUN apk --no-cache add ca-certificates
WORKDIR /usr/bin
COPY --from=builder /out/aapije /usr/bin/aapije
CMD ["/usr/bin/aapije"]
