// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: access.sql

package postgres

import (
	"context"

	"github.com/lib/pq"
)

const checkUserTokenHasAccess = `-- name: CheckUserTokenHasAccess :one
WITH usr AS (
	SELECT user_tokens.user_uuid AS uuid
	FROM user_tokens
	WHERE user_tokens.token_hash = sha256($3)
	LIMIT 1
)
SELECT COALESCE((
	SELECT
		EXISTS (
			SELECT 1
			FROM user_groups
			INNER JOIN group_policies ON group_policies.group_uuid = user_groups.group_uuid
			WHERE user_groups.user_uuid = usr.uuid
			AND group_policies.action = $1::policy_action
			AND group_policies.effect = 'allow'
			AND $2::TEXT LIKE group_policies.resource
		)
		AND NOT EXISTS (
			SELECT 1
			FROM user_groups
			INNER JOIN group_policies ON group_policies.group_uuid = user_groups.group_uuid
			WHERE user_groups.user_uuid = usr.uuid
			AND group_policies.action = $1::policy_action
			AND group_policies.effect = 'deny'
			AND $2::TEXT LIKE group_policies.resource
		)
	FROM usr
	LIMIT 1
), false)::boolean AS access
`

type CheckUserTokenHasAccessParams struct {
	Action   PolicyAction
	Resource string
	Token    []byte
}

func (q *Queries) CheckUserTokenHasAccess(ctx context.Context, arg CheckUserTokenHasAccessParams) (bool, error) {
	row := q.queryRow(ctx, q.checkUserTokenHasAccessStmt, checkUserTokenHasAccess, arg.Action, arg.Resource, arg.Token)
	var access bool
	err := row.Scan(&access)
	return access, err
}

const checkUserTokenHasAccessMany = `-- name: CheckUserTokenHasAccessMany :one
WITH usr AS (
	SELECT user_tokens.user_uuid AS uuid
	FROM user_tokens
	WHERE user_tokens.token_hash = sha256($1)
	LIMIT 1
), usr_r AS (
	SELECT
		usr.uuid,
		$2::policy_action AS action,
		unnest((SELECT $3::TEXT[]))::TEXT AS resource
	FROM usr
)
SELECT
	COALESCE(bool_and(
		EXISTS (
			SELECT 1
			FROM user_groups
			INNER JOIN group_policies ON group_policies.group_uuid = user_groups.group_uuid
			WHERE user_groups.user_uuid = usr_r.uuid
			AND group_policies.action = usr_r.action
			AND group_policies.effect = 'allow'
			AND usr_r.resource LIKE group_policies.resource
		)
		AND NOT EXISTS (
			SELECT 1
			FROM user_groups
			INNER JOIN group_policies ON group_policies.group_uuid = user_groups.group_uuid
			WHERE user_groups.user_uuid = usr_r.uuid
			AND group_policies.action = usr_r.action
			AND group_policies.effect = 'deny'
			AND usr_r.resource LIKE group_policies.resource
		)
	), false)::boolean AS access
FROM usr_r
`

type CheckUserTokenHasAccessManyParams struct {
	Token     []byte
	Action    PolicyAction
	Resources []string
}

func (q *Queries) CheckUserTokenHasAccessMany(ctx context.Context, arg CheckUserTokenHasAccessManyParams) (bool, error) {
	row := q.queryRow(ctx, q.checkUserTokenHasAccessManyStmt, checkUserTokenHasAccessMany, arg.Token, arg.Action, pq.Array(arg.Resources))
	var access bool
	err := row.Scan(&access)
	return access, err
}
