// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: access.sql

package postgres

import (
	"context"

	"github.com/lib/pq"
)

const checkUserTokenHasAccess = `-- name: CheckUserTokenHasAccess :one
WITH usr AS (
	SELECT user_tokens.user_uuid AS uuid
	FROM user_tokens
	WHERE user_tokens.token_hash = sha256($3)
	LIMIT 1
)
SELECT COALESCE((
	SELECT match.effect = 'allow'
	FROM usr
	LEFT JOIN LATERAL (
		SELECT group_policies.effect
		FROM user_groups
		INNER JOIN group_policies ON group_policies.group_uuid = user_groups.group_uuid
		WHERE user_groups.user_uuid = usr.uuid
		AND group_policies.action = $1::policy_action
		AND $2::TEXT LIKE group_policies.resource
		ORDER BY group_policies.priority ASC,
			CASE WHEN group_policies.effect = 'deny' THEN 0 ELSE 1 END ASC
		LIMIT 1
	) AS match ON true
	LIMIT 1
), false)::boolean AS access
`

type CheckUserTokenHasAccessParams struct {
	Action   PolicyAction
	Resource string
	Token    []byte
}

func (q *Queries) CheckUserTokenHasAccess(ctx context.Context, arg CheckUserTokenHasAccessParams) (bool, error) {
	row := q.queryRow(ctx, q.checkUserTokenHasAccessStmt, checkUserTokenHasAccess, arg.Action, arg.Resource, arg.Token)
	var access bool
	err := row.Scan(&access)
	return access, err
}

const checkUserTokenHasAccessMany = `-- name: CheckUserTokenHasAccessMany :one
WITH usr AS (
	SELECT user_tokens.user_uuid AS uuid
	FROM user_tokens
	WHERE user_tokens.token_hash = sha256($1)
	LIMIT 1
), usr_r AS (
	SELECT
		usr.uuid,
		$2::policy_action AS action,
		unnest((SELECT $3::TEXT[]))::TEXT AS resource
	FROM usr
	)
SELECT
	COALESCE(bool_and(match.effect = 'allow'), false)::boolean AS access
FROM usr_r
LEFT JOIN LATERAL (
	SELECT group_policies.effect
	FROM user_groups
	INNER JOIN group_policies ON group_policies.group_uuid = user_groups.group_uuid
	WHERE user_groups.user_uuid = usr_r.uuid
	AND group_policies.action = usr_r.action
	AND usr_r.resource LIKE group_policies.resource
	ORDER BY group_policies.priority ASC,
		CASE WHEN group_policies.effect = 'deny' THEN 0 ELSE 1 END ASC
	LIMIT 1
) AS match ON true
`

type CheckUserTokenHasAccessManyParams struct {
	Token     []byte
	Action    PolicyAction
	Resources []string
}

func (q *Queries) CheckUserTokenHasAccessMany(ctx context.Context, arg CheckUserTokenHasAccessManyParams) (bool, error) {
	row := q.queryRow(ctx, q.checkUserTokenHasAccessManyStmt, checkUserTokenHasAccessMany, arg.Token, arg.Action, pq.Array(arg.Resources))
	var access bool
	err := row.Scan(&access)
	return access, err
}
