// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: group_policies.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const findPoliciesByGroup = `-- name: FindPoliciesByGroup :many
SELECT uuid, group_uuid, priority, effect, action, resource FROM group_policies
WHERE group_policies.group_uuid = $1
ORDER BY priority
`

func (q *Queries) FindPoliciesByGroup(ctx context.Context, argUuid uuid.UUID) ([]GroupPolicy, error) {
	rows, err := q.query(ctx, q.findPoliciesByGroupStmt, findPoliciesByGroup, argUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupPolicy{}
	for rows.Next() {
		var i GroupPolicy
		if err := rows.Scan(
			&i.Uuid,
			&i.GroupUuid,
			&i.Priority,
			&i.Effect,
			&i.Action,
			&i.Resource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPoliciesByToken = `-- name: FindPoliciesByToken :many
SELECT group_policies.uuid, group_policies.group_uuid, group_policies.priority, group_policies.effect, group_policies.action, group_policies.resource
FROM group_policies
INNER JOIN user_groups ON user_groups.group_uuid = group_policies.group_uuid
INNER JOIN user_tokens ON user_tokens.user_uuid = user_groups.user_uuid
WHERE user_tokens.token_hash = sha256($1)
ORDER BY priority
`

func (q *Queries) FindPoliciesByToken(ctx context.Context, token []byte) ([]GroupPolicy, error) {
	rows, err := q.query(ctx, q.findPoliciesByTokenStmt, findPoliciesByToken, token)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupPolicy{}
	for rows.Next() {
		var i GroupPolicy
		if err := rows.Scan(
			&i.Uuid,
			&i.GroupUuid,
			&i.Priority,
			&i.Effect,
			&i.Action,
			&i.Resource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPoliciesByUser = `-- name: FindPoliciesByUser :many
SELECT group_policies.uuid, group_policies.group_uuid, group_policies.priority, group_policies.effect, group_policies.action, group_policies.resource
FROM group_policies, user_groups
WHERE user_groups.group_uuid = group_policies.group_uuid
AND user_groups.user_uuid = $1
ORDER BY priority
`

func (q *Queries) FindPoliciesByUser(ctx context.Context, argUuid uuid.UUID) ([]GroupPolicy, error) {
	rows, err := q.query(ctx, q.findPoliciesByUserStmt, findPoliciesByUser, argUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupPolicy{}
	for rows.Next() {
		var i GroupPolicy
		if err := rows.Scan(
			&i.Uuid,
			&i.GroupUuid,
			&i.Priority,
			&i.Effect,
			&i.Action,
			&i.Resource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
