// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups(name)
VALUES($1)
RETURNING uuid, name
`

func (q *Queries) CreateGroup(ctx context.Context, name string) (Group, error) {
	row := q.queryRow(ctx, q.createGroupStmt, createGroup, name)
	var i Group
	err := row.Scan(&i.Uuid, &i.Name)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :execrows
DELETE FROM groups
WHERE groups.uuid = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, argUuid uuid.UUID) (int64, error) {
	result, err := q.exec(ctx, q.deleteGroupStmt, deleteGroup, argUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const existsGroup = `-- name: ExistsGroup :one
SELECT COUNT(*) AS count
FROM groups
WHERE groups.uuid = $1
`

func (q *Queries) ExistsGroup(ctx context.Context, argUuid uuid.UUID) (int64, error) {
	row := q.queryRow(ctx, q.existsGroupStmt, existsGroup, argUuid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findGroupByUuid = `-- name: FindGroupByUuid :one
SELECT uuid, name FROM groups
WHERE uuid = $1
LIMIT 1
`

func (q *Queries) FindGroupByUuid(ctx context.Context, argUuid uuid.UUID) (Group, error) {
	row := q.queryRow(ctx, q.findGroupByUuidStmt, findGroupByUuid, argUuid)
	var i Group
	err := row.Scan(&i.Uuid, &i.Name)
	return i, err
}

const findGroups = `-- name: FindGroups :many
WITH usr AS (
	SELECT user_tokens.user_uuid AS uuid
	FROM user_tokens
	WHERE user_tokens.token_hash = sha256($1)
	LIMIT 1
), permitted_groups AS (
	SELECT uuid, name
	FROM groups
	WHERE EXISTS (
		SELECT 1
		FROM usr
		INNER JOIN user_groups ON user_groups.user_uuid = usr.uuid
		INNER JOIN group_policies ON group_policies.group_uuid = user_groups.group_uuid
		WHERE group_policies.action = 'read'
		AND group_policies.effect = 'allow'
		AND ('groups/'||groups.uuid) LIKE group_policies.resource
	)
	AND NOT EXISTS (
		SELECT 1
		FROM usr
		INNER JOIN user_groups ON user_groups.user_uuid = usr.uuid
		INNER JOIN group_policies ON group_policies.group_uuid = user_groups.group_uuid
		WHERE group_policies.action = 'read'
		AND group_policies.effect = 'deny'
		AND ('groups/'||groups.uuid) LIKE group_policies.resource
	)
	ORDER BY name
	LIMIT $3::BIGINT
	OFFSET $2::BIGINT
)
SELECT uuid, name
FROM permitted_groups
`

type FindGroupsParams struct {
	Token     []byte
	ArgOffset int64
	ArgLimit  int64
}

type FindGroupsRow struct {
	Uuid uuid.UUID
	Name string
}

func (q *Queries) FindGroups(ctx context.Context, arg FindGroupsParams) ([]FindGroupsRow, error) {
	rows, err := q.query(ctx, q.findGroupsStmt, findGroups, arg.Token, arg.ArgOffset, arg.ArgLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindGroupsRow{}
	for rows.Next() {
		var i FindGroupsRow
		if err := rows.Scan(&i.Uuid, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findGroupsByUser = `-- name: FindGroupsByUser :many
SELECT groups.uuid, groups.name
FROM groups, user_groups
WHERE groups.uuid = user_groups.group_uuid
AND user_groups.user_uuid = $1
`

func (q *Queries) FindGroupsByUser(ctx context.Context, argUuid uuid.UUID) ([]Group, error) {
	rows, err := q.query(ctx, q.findGroupsByUserStmt, findGroupsByUser, argUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(&i.Uuid, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGroupNameByUUID = `-- name: SetGroupNameByUUID :execrows
UPDATE groups
SET name = $1
WHERE groups.uuid = $2
`

type SetGroupNameByUUIDParams struct {
	Name string
	Uuid uuid.UUID
}

func (q *Queries) SetGroupNameByUUID(ctx context.Context, arg SetGroupNameByUUIDParams) (int64, error) {
	result, err := q.exec(ctx, q.setGroupNameByUUIDStmt, setGroupNameByUUID, arg.Name, arg.Uuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
