// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type AccountState string

const (
	AccountStateActive   AccountState = "active"
	AccountStateInactive AccountState = "inactive"
	AccountStateArchived AccountState = "archived"
)

func (e *AccountState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountState(s)
	case string:
		*e = AccountState(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountState: %T", src)
	}
	return nil
}

type NullAccountState struct {
	AccountState AccountState
	Valid        bool // Valid is true if AccountState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountState) Scan(value interface{}) error {
	if value == nil {
		ns.AccountState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountState), nil
}

type AlertSeverity string

const (
	AlertSeveritySecurity      AlertSeverity = "security"
	AlertSeverityCritical      AlertSeverity = "critical"
	AlertSeverityMajor         AlertSeverity = "major"
	AlertSeverityMinor         AlertSeverity = "minor"
	AlertSeverityWarning       AlertSeverity = "warning"
	AlertSeverityInformational AlertSeverity = "informational"
	AlertSeverityDebug         AlertSeverity = "debug"
	AlertSeverityTrace         AlertSeverity = "trace"
	AlertSeverityIndeterminate AlertSeverity = "indeterminate"
)

func (e *AlertSeverity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlertSeverity(s)
	case string:
		*e = AlertSeverity(s)
	default:
		return fmt.Errorf("unsupported scan type for AlertSeverity: %T", src)
	}
	return nil
}

type NullAlertSeverity struct {
	AlertSeverity AlertSeverity
	Valid         bool // Valid is true if AlertSeverity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlertSeverity) Scan(value interface{}) error {
	if value == nil {
		ns.AlertSeverity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlertSeverity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlertSeverity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlertSeverity), nil
}

type AlertStatus string

const (
	AlertStatusOpen        AlertStatus = "open"
	AlertStatusClose       AlertStatus = "close"
	AlertStatusExpire      AlertStatus = "expire"
	AlertStatusShelve      AlertStatus = "shelve"
	AlertStatusAcknowledge AlertStatus = "acknowledge"
	AlertStatusUnknown     AlertStatus = "unknown"
)

func (e *AlertStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlertStatus(s)
	case string:
		*e = AlertStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AlertStatus: %T", src)
	}
	return nil
}

type NullAlertStatus struct {
	AlertStatus AlertStatus
	Valid       bool // Valid is true if AlertStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlertStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AlertStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlertStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlertStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlertStatus), nil
}

type PolicyAction string

const (
	PolicyActionCreate PolicyAction = "create"
	PolicyActionRead   PolicyAction = "read"
	PolicyActionUpdate PolicyAction = "update"
	PolicyActionDelete PolicyAction = "delete"
)

func (e *PolicyAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PolicyAction(s)
	case string:
		*e = PolicyAction(s)
	default:
		return fmt.Errorf("unsupported scan type for PolicyAction: %T", src)
	}
	return nil
}

type NullPolicyAction struct {
	PolicyAction PolicyAction
	Valid        bool // Valid is true if PolicyAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPolicyAction) Scan(value interface{}) error {
	if value == nil {
		ns.PolicyAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PolicyAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPolicyAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PolicyAction), nil
}

type PolicyEffect string

const (
	PolicyEffectAllow PolicyEffect = "allow"
	PolicyEffectDeny  PolicyEffect = "deny"
)

func (e *PolicyEffect) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PolicyEffect(s)
	case string:
		*e = PolicyEffect(s)
	default:
		return fmt.Errorf("unsupported scan type for PolicyEffect: %T", src)
	}
	return nil
}

type NullPolicyEffect struct {
	PolicyEffect PolicyEffect
	Valid        bool // Valid is true if PolicyEffect is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPolicyEffect) Scan(value interface{}) error {
	if value == nil {
		ns.PolicyEffect, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PolicyEffect.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPolicyEffect) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PolicyEffect), nil
}

type ThingState string

const (
	ThingStateActive   ThingState = "active"
	ThingStateInactive ThingState = "inactive"
	ThingStatePassive  ThingState = "passive"
	ThingStateArchived ThingState = "archived"
)

func (e *ThingState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ThingState(s)
	case string:
		*e = ThingState(s)
	default:
		return fmt.Errorf("unsupported scan type for ThingState: %T", src)
	}
	return nil
}

type NullThingState struct {
	ThingState ThingState
	Valid      bool // Valid is true if ThingState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullThingState) Scan(value interface{}) error {
	if value == nil {
		ns.ThingState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ThingState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullThingState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ThingState), nil
}

type Alert struct {
	Uuid             uuid.UUID
	Resource         string
	Environment      string
	Event            string
	Severity         AlertSeverity
	Status           AlertStatus
	Service          []string
	Value            string
	Description      string
	Origin           string
	Tags             []string
	Created          time.Time
	Timeout          int32
	Rawdata          []byte
	Duplicate        int32
	PreviousSeverity AlertSeverity
	LastReceiveTime  sql.NullTime
}

type Dataset struct {
	Uuid      uuid.UUID
	Name      string
	Format    string
	Content   []byte
	Checksum  []byte
	Size      int32
	BelongsTo uuid.NullUUID
	Created   time.Time
	Updated   time.Time
	CreatedBy uuid.NullUUID
	UpdatedBy uuid.NullUUID
	Tags      []string
}

type Group struct {
	Uuid uuid.UUID
	Name string
}

type GroupPolicy struct {
	Uuid      uuid.UUID
	GroupUuid uuid.UUID
	Priority  int32
	Effect    PolicyEffect
	Action    PolicyAction
	Resource  string
}

type Program struct {
	Uuid     uuid.UUID
	Name     string
	Type     string
	State    string
	Schedule string
	Deadline int32
	Language string
	Tags     []string
}

type ProgramCodeRevision struct {
	ProgramUuid uuid.UUID
	Revision    int32
	Created     time.Time
	Signed      sql.NullTime
	CreatedBy   uuid.NullUUID
	SignedBy    uuid.NullUUID
	Code        []byte
	Checksum    []byte
}

type Thing struct {
	Uuid      uuid.UUID
	Name      string
	Type      sql.NullString
	State     ThingState
	CreatedBy uuid.NullUUID
	Tags      []string
}

type ThingDep struct {
	Parent uuid.UUID
	Child  uuid.UUID
}

type Timeseries struct {
	Uuid       uuid.UUID
	ThingUuid  uuid.NullUUID
	Name       string
	SiUnit     string
	LowerBound sql.NullFloat64
	UpperBound sql.NullFloat64
	CreatedBy  uuid.NullUUID
	Tags       []string
}

type Tsdata0 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata1 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata10 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata100 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata101 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata102 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata103 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata104 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata105 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata106 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata107 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata108 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata109 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata11 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata110 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata111 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata112 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata113 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata114 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata115 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata116 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata117 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata118 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata119 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata12 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata120 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata121 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata122 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata123 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata124 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata125 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata126 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata127 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata128 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata129 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata13 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata130 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata131 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata132 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata133 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata134 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata135 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata136 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata137 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata138 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata139 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata14 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata140 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata141 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata142 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata143 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata144 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata145 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata146 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata147 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata148 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata149 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata15 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata150 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata151 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata152 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata153 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata154 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata155 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata156 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata157 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata158 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata159 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata16 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata160 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata161 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata162 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata163 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata164 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata165 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata166 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata167 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata168 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata169 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata17 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata170 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata171 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata172 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata173 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata174 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata175 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata176 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata177 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata178 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata179 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata18 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata180 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata181 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata182 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata183 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata184 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata185 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata186 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata187 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata188 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata189 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata19 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata190 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata191 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata192 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata193 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata194 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata195 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata196 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata197 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata198 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata199 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata2 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata20 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata200 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata201 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata202 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata203 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata204 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata205 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata206 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata207 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata208 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata209 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata21 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata210 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata211 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata212 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata213 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata214 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata215 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata216 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata217 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata218 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata219 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata22 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata220 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata221 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata222 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata223 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata224 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata225 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata226 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata227 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata228 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata229 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata23 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata230 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata231 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata232 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata233 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata234 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata235 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata236 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata237 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata238 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata239 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata24 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata240 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata241 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata242 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata243 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata244 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata245 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata246 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata247 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata248 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata249 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata25 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata250 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata251 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata252 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata253 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata254 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata255 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata26 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata27 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata28 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata29 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata3 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata30 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata31 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata32 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata33 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata34 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata35 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata36 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata37 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata38 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata39 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata4 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata40 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata41 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata42 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata43 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata44 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata45 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata46 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata47 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata48 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata49 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata5 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata50 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata51 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata52 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata53 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata54 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata55 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata56 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata57 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata58 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata59 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata6 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata60 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata61 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata62 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata63 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata64 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata65 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata66 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata67 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata68 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata69 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata7 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata70 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata71 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata72 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata73 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata74 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata75 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata76 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata77 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata78 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata79 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata8 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata80 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata81 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata82 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata83 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata84 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata85 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata86 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata87 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata88 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata89 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata9 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata90 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata91 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata92 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata93 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata94 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata95 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata96 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata97 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata98 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdata99 struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type Tsdatum struct {
	TsUuid    uuid.UUID
	Value     float64
	Ts        time.Time
	CreatedBy uuid.NullUUID
}

type User struct {
	Uuid  uuid.UUID
	Name  string
	State AccountState
}

type UserGroup struct {
	UserUuid  uuid.UUID
	GroupUuid uuid.UUID
}

type UserToken struct {
	Uuid      uuid.UUID
	UserUuid  uuid.UUID
	Name      string
	TokenHash []byte
	Created   time.Time
}

type VAlert struct {
	Uuid             uuid.UUID
	Resource         string
	Environment      string
	Event            string
	Severity         AlertSeverity
	PreviousSeverity AlertSeverity
	Status           AlertStatus
	Description      string
	Value            string
	Origin           string
	Created          time.Time
	LastReceiveTime  sql.NullTime
	Timeout          int32
	Duplicate        int32
	Service          []string
	Tags             []string
	Rawdata          []byte
}
