// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: programs.sql

package postgres

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createCodeRevision = `-- name: CreateCodeRevision :one
INSERT INTO program_code_revisions (program_uuid, revision, created_by, code, checksum)
VALUES (
	$1,
	COALESCE((
		SELECT MAX(pcr.revision) + 1
		FROM program_code_revisions AS pcr
		WHERE pcr.program_uuid = $1
	), 0)::INTEGER,
	$2,
	$3,
	sha256($3)
) RETURNING
	program_uuid,
	revision,
	created,
	created_by,
	signed,
	signed_by,
	encode(checksum, 'hex') AS checksum
`

type CreateCodeRevisionParams struct {
	ProgramUuid uuid.UUID
	CreatedBy   uuid.NullUUID
	Code        []byte
}

type CreateCodeRevisionRow struct {
	ProgramUuid uuid.UUID
	Revision    int32
	Created     time.Time
	CreatedBy   uuid.NullUUID
	Signed      sql.NullTime
	SignedBy    uuid.NullUUID
	Checksum    string
}

func (q *Queries) CreateCodeRevision(ctx context.Context, arg CreateCodeRevisionParams) (CreateCodeRevisionRow, error) {
	row := q.queryRow(ctx, q.createCodeRevisionStmt, createCodeRevision, arg.ProgramUuid, arg.CreatedBy, arg.Code)
	var i CreateCodeRevisionRow
	err := row.Scan(
		&i.ProgramUuid,
		&i.Revision,
		&i.Created,
		&i.CreatedBy,
		&i.Signed,
		&i.SignedBy,
		&i.Checksum,
	)
	return i, err
}

const createProgram = `-- name: CreateProgram :one
WITH p AS (
	INSERT INTO programs (name, type, state, schedule, deadline, language, tags)
	VALUES (
		$1,
		$2,
		$3,
		$4,
		$5,
		$6,
		$7
	) RETURNING uuid, name, type, state, schedule, deadline, language, tags
), grp AS (
	SELECT groups.uuid
	FROM groups, user_groups
	WHERE user_groups.group_uuid = groups.uuid
	AND user_groups.user_uuid = $8
	AND groups.uuid = (
		SELECT users.uuid
		FROM users
		WHERE users.name = groups.name
	)
	LIMIT 1
), grp_policies AS (
	INSERT INTO group_policies(group_uuid, priority, effect, action, resource)
	VALUES (
		(SELECT uuid FROM grp), 0, 'allow', 'create','programs/'||(SELECT uuid FROM p)||'/%'
	), (
		(SELECT uuid FROM grp), 0, 'allow', 'read','programs/'||(SELECT uuid FROM p)||'/%'
	), (
		(SELECT uuid FROM grp), 0, 'allow', 'update','programs/'||(SELECT uuid FROM p)||'/%'
	), (
		(SELECT uuid FROM grp), 0, 'allow', 'delete','programs/'||(SELECT uuid FROM p)||'/%'
	)
)
SELECT uuid, name, type, state, schedule, deadline, language, tags
FROM p LIMIT 1
`

type CreateProgramParams struct {
	Name      string
	Type      string
	State     string
	Schedule  string
	Deadline  int32
	Language  string
	Tags      []string
	CreatedBy uuid.UUID
}

type CreateProgramRow struct {
	Uuid     uuid.UUID
	Name     string
	Type     string
	State    string
	Schedule string
	Deadline int32
	Language string
	Tags     []string
}

func (q *Queries) CreateProgram(ctx context.Context, arg CreateProgramParams) (CreateProgramRow, error) {
	row := q.queryRow(ctx, q.createProgramStmt, createProgram,
		arg.Name,
		arg.Type,
		arg.State,
		arg.Schedule,
		arg.Deadline,
		arg.Language,
		pq.Array(arg.Tags),
		arg.CreatedBy,
	)
	var i CreateProgramRow
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.Type,
		&i.State,
		&i.Schedule,
		&i.Deadline,
		&i.Language,
		pq.Array(&i.Tags),
	)
	return i, err
}

const deleteProgram = `-- name: DeleteProgram :execrows
DELETE FROM programs
WHERE programs.uuid = $1
`

func (q *Queries) DeleteProgram(ctx context.Context, argUuid uuid.UUID) (int64, error) {
	result, err := q.exec(ctx, q.deleteProgramStmt, deleteProgram, argUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteProgramCodeRevision = `-- name: DeleteProgramCodeRevision :execrows
DELETE FROM program_code_revisions
WHERE program_uuid = $1
AND revision = $2
`

type DeleteProgramCodeRevisionParams struct {
	ProgramUuid uuid.UUID
	Revision    int32
}

func (q *Queries) DeleteProgramCodeRevision(ctx context.Context, arg DeleteProgramCodeRevisionParams) (int64, error) {
	result, err := q.exec(ctx, q.deleteProgramCodeRevisionStmt, deleteProgramCodeRevision, arg.ProgramUuid, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const existsProgram = `-- name: ExistsProgram :one
SELECT COUNT(*) AS count
FROM programs
WHERE programs.uuid = $1
`

func (q *Queries) ExistsProgram(ctx context.Context, argUuid uuid.UUID) (int64, error) {
	row := q.queryRow(ctx, q.existsProgramStmt, existsProgram, argUuid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findAllModules = `-- name: FindAllModules :many
SELECT
	programs.name,
	pcr.program_uuid,
        programs.type,
        programs.schedule,
        programs.deadline,
        programs.language,
        pcr.revision,
        pcr.code,
	encode(pcr.checksum, 'hex') AS checksum
FROM program_code_revisions AS pcr, programs
WHERE programs.uuid = pcr.program_uuid
AND programs.state = 'active'
AND programs.type = 'module'
AND pcr.signed IS NOT NULL
ORDER BY
	pcr.program_uuid,
	pcr.revision DESC
`

type FindAllModulesRow struct {
	Name        string
	ProgramUuid uuid.UUID
	Type        string
	Schedule    string
	Deadline    int32
	Language    string
	Revision    int32
	Code        []byte
	Checksum    string
}

func (q *Queries) FindAllModules(ctx context.Context) ([]FindAllModulesRow, error) {
	rows, err := q.query(ctx, q.findAllModulesStmt, findAllModules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindAllModulesRow{}
	for rows.Next() {
		var i FindAllModulesRow
		if err := rows.Scan(
			&i.Name,
			&i.ProgramUuid,
			&i.Type,
			&i.Schedule,
			&i.Deadline,
			&i.Language,
			&i.Revision,
			&i.Code,
			&i.Checksum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllRoutineRevisions = `-- name: FindAllRoutineRevisions :many
WITH p AS (
	SELECT
        	pcr.program_uuid, pcr.revision, pcr.created, pcr.signed, pcr.created_by, pcr.signed_by, pcr.code, pcr.checksum,
		programs.uuid, programs.name, programs.type, programs.state, programs.schedule, programs.deadline, programs.language, programs.tags,
		RANK () OVER (
			PARTITION BY pcr.program_uuid
			ORDER BY revision DESC
		) revision_rank
	FROM program_code_revisions AS pcr
	INNER JOIN programs ON programs.uuid = pcr.program_uuid
	WHERE pcr.signed IS NOT NULL
	AND programs.type IN ('routine', 'webhook')
	AND programs.state = 'active'
)
SELECT
	p.name,
	p.program_uuid,
        p.type,
        p.schedule,
        p.deadline,
        p.language,
        p.revision,
        p.code,
        encode(p.checksum, 'hex') AS checksum
FROM p
WHERE revision_rank = 1
`

type FindAllRoutineRevisionsRow struct {
	Name        string
	ProgramUuid uuid.UUID
	Type        string
	Schedule    string
	Deadline    int32
	Language    string
	Revision    int32
	Code        []byte
	Checksum    string
}

func (q *Queries) FindAllRoutineRevisions(ctx context.Context) ([]FindAllRoutineRevisionsRow, error) {
	rows, err := q.query(ctx, q.findAllRoutineRevisionsStmt, findAllRoutineRevisions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindAllRoutineRevisionsRow{}
	for rows.Next() {
		var i FindAllRoutineRevisionsRow
		if err := rows.Scan(
			&i.Name,
			&i.ProgramUuid,
			&i.Type,
			&i.Schedule,
			&i.Deadline,
			&i.Language,
			&i.Revision,
			&i.Code,
			&i.Checksum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findProgramByUUID = `-- name: FindProgramByUUID :one
SELECT
	uuid, name, type, state, schedule, deadline, language, tags
FROM programs
WHERE programs.uuid = $1
LIMIT 1
`

func (q *Queries) FindProgramByUUID(ctx context.Context, argUuid uuid.UUID) (Program, error) {
	row := q.queryRow(ctx, q.findProgramByUUIDStmt, findProgramByUUID, argUuid)
	var i Program
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.Type,
		&i.State,
		&i.Schedule,
		&i.Deadline,
		&i.Language,
		pq.Array(&i.Tags),
	)
	return i, err
}

const findProgramCodeRevisions = `-- name: FindProgramCodeRevisions :many
SELECT
	revision, created, created_by, signed, signed_by, encode(checksum, 'hex') AS checksum
FROM
	program_code_revisions
WHERE
	program_uuid = $1
ORDER BY revision ASC
`

type FindProgramCodeRevisionsRow struct {
	Revision  int32
	Created   time.Time
	CreatedBy uuid.NullUUID
	Signed    sql.NullTime
	SignedBy  uuid.NullUUID
	Checksum  string
}

func (q *Queries) FindProgramCodeRevisions(ctx context.Context, programUuid uuid.UUID) ([]FindProgramCodeRevisionsRow, error) {
	rows, err := q.query(ctx, q.findProgramCodeRevisionsStmt, findProgramCodeRevisions, programUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindProgramCodeRevisionsRow{}
	for rows.Next() {
		var i FindProgramCodeRevisionsRow
		if err := rows.Scan(
			&i.Revision,
			&i.Created,
			&i.CreatedBy,
			&i.Signed,
			&i.SignedBy,
			&i.Checksum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPrograms = `-- name: FindPrograms :many
WITH usr AS (
	SELECT user_tokens.user_uuid AS uuid
	FROM user_tokens
	WHERE user_tokens.token_hash = sha256($1)
	LIMIT 1
), permitted_programs AS (
	SELECT uuid, name, type, state, schedule, deadline, language, tags
	FROM programs
	WHERE EXISTS (
		SELECT 1
		FROM usr
		INNER JOIN user_groups ON user_groups.user_uuid = usr.uuid
		INNER JOIN group_policies ON group_policies.group_uuid = user_groups.group_uuid
		WHERE group_policies.action = 'read'
		AND group_policies.effect = 'allow'
		AND ('programs/'||programs.uuid) LIKE group_policies.resource
	)
	AND NOT EXISTS (
		SELECT 1
		FROM usr
		INNER JOIN user_groups ON user_groups.user_uuid = usr.uuid
		INNER JOIN group_policies ON group_policies.group_uuid = user_groups.group_uuid
		WHERE group_policies.action = 'read'
		AND group_policies.effect = 'deny'
		AND ('programs/'||programs.uuid) LIKE group_policies.resource
	)
	ORDER BY name
	LIMIT $3::BIGINT
	OFFSET $2::BIGINT
)
SELECT
	uuid, name, type, state, schedule, deadline, language, tags
FROM permitted_programs
`

type FindProgramsParams struct {
	Token     []byte
	ArgOffset int64
	ArgLimit  int64
}

type FindProgramsRow struct {
	Uuid     uuid.UUID
	Name     string
	Type     string
	State    string
	Schedule string
	Deadline int32
	Language string
	Tags     []string
}

func (q *Queries) FindPrograms(ctx context.Context, arg FindProgramsParams) ([]FindProgramsRow, error) {
	rows, err := q.query(ctx, q.findProgramsStmt, findPrograms, arg.Token, arg.ArgOffset, arg.ArgLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindProgramsRow{}
	for rows.Next() {
		var i FindProgramsRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.Type,
			&i.State,
			&i.Schedule,
			&i.Deadline,
			&i.Language,
			pq.Array(&i.Tags),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findProgramsByTags = `-- name: FindProgramsByTags :many
WITH usr AS (
	SELECT user_tokens.user_uuid AS uuid
	FROM user_tokens
	WHERE user_tokens.token_hash = sha256($1)
	LIMIT 1
), permitted_programs AS (
	SELECT uuid, name, type, state, schedule, deadline, language, tags
	FROM programs
	WHERE $2 && programs.tags
	AND EXISTS (
		SELECT 1
		FROM usr
		INNER JOIN user_groups ON user_groups.user_uuid = usr.uuid
		INNER JOIN group_policies ON group_policies.group_uuid = user_groups.group_uuid
		WHERE group_policies.action = 'read'
		AND group_policies.effect = 'allow'
		AND ('programs/'||programs.uuid) LIKE group_policies.resource
	)
	AND NOT EXISTS (
		SELECT 1
		FROM usr
		INNER JOIN user_groups ON user_groups.user_uuid = usr.uuid
		INNER JOIN group_policies ON group_policies.group_uuid = user_groups.group_uuid
		WHERE group_policies.action = 'read'
		AND group_policies.effect = 'deny'
		AND ('programs/'||programs.uuid) LIKE group_policies.resource
	)
	ORDER BY name
	LIMIT $4::BIGINT
	OFFSET $3::BIGINT
)
SELECT uuid, name, type, state, schedule, deadline, language, tags
FROM permitted_programs
`

type FindProgramsByTagsParams struct {
	Token     []byte
	Tags      []string
	ArgOffset int64
	ArgLimit  int64
}

type FindProgramsByTagsRow struct {
	Uuid     uuid.UUID
	Name     string
	Type     string
	State    string
	Schedule string
	Deadline int32
	Language string
	Tags     []string
}

func (q *Queries) FindProgramsByTags(ctx context.Context, arg FindProgramsByTagsParams) ([]FindProgramsByTagsRow, error) {
	rows, err := q.query(ctx, q.findProgramsByTagsStmt, findProgramsByTags,
		arg.Token,
		pq.Array(arg.Tags),
		arg.ArgOffset,
		arg.ArgLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindProgramsByTagsRow{}
	for rows.Next() {
		var i FindProgramsByTagsRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.Type,
			&i.State,
			&i.Schedule,
			&i.Deadline,
			&i.Language,
			pq.Array(&i.Tags),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNamedModuleCodeAtHead = `-- name: GetNamedModuleCodeAtHead :one
SELECT
	code
FROM program_code_revisions, programs
WHERE program_uuid = programs.uuid
AND programs.name = $1
AND programs.type = 'module'
AND programs.state = 'active'
AND programs.language = $2
AND program_code_revisions.signed IS NOT NULL
ORDER BY revision DESC
LIMIT 1
`

type GetNamedModuleCodeAtHeadParams struct {
	Name     string
	Language string
}

func (q *Queries) GetNamedModuleCodeAtHead(ctx context.Context, arg GetNamedModuleCodeAtHeadParams) ([]byte, error) {
	row := q.queryRow(ctx, q.getNamedModuleCodeAtHeadStmt, getNamedModuleCodeAtHead, arg.Name, arg.Language)
	var code []byte
	err := row.Scan(&code)
	return code, err
}

const getNamedModuleCodeAtRevision = `-- name: GetNamedModuleCodeAtRevision :one
SELECT
	code
FROM program_code_revisions, programs
WHERE program_uuid = programs.uuid
AND programs.name = $1
AND programs.type = 'module'
AND programs.state = 'active'
AND programs.language = $2
AND program_code_revisions.signed IS NOT NULL
AND program_code_revisions.revision = $3
LIMIT 1
`

type GetNamedModuleCodeAtRevisionParams struct {
	Name     string
	Language string
	Revision int32
}

func (q *Queries) GetNamedModuleCodeAtRevision(ctx context.Context, arg GetNamedModuleCodeAtRevisionParams) ([]byte, error) {
	row := q.queryRow(ctx, q.getNamedModuleCodeAtRevisionStmt, getNamedModuleCodeAtRevision, arg.Name, arg.Language, arg.Revision)
	var code []byte
	err := row.Scan(&code)
	return code, err
}

const getProgramCodeAtHead = `-- name: GetProgramCodeAtHead :one
SELECT
	code, revision
FROM program_code_revisions
WHERE program_uuid = $1
ORDER BY revision DESC
LIMIT 1
`

type GetProgramCodeAtHeadRow struct {
	Code     []byte
	Revision int32
}

func (q *Queries) GetProgramCodeAtHead(ctx context.Context, programUuid uuid.UUID) (GetProgramCodeAtHeadRow, error) {
	row := q.queryRow(ctx, q.getProgramCodeAtHeadStmt, getProgramCodeAtHead, programUuid)
	var i GetProgramCodeAtHeadRow
	err := row.Scan(&i.Code, &i.Revision)
	return i, err
}

const getProgramCodeAtRevision = `-- name: GetProgramCodeAtRevision :one
SELECT
	code
FROM program_code_revisions
WHERE program_uuid = $1
AND revision = $2
LIMIT 1
`

type GetProgramCodeAtRevisionParams struct {
	ProgramUuid uuid.UUID
	Revision    int32
}

func (q *Queries) GetProgramCodeAtRevision(ctx context.Context, arg GetProgramCodeAtRevisionParams) ([]byte, error) {
	row := q.queryRow(ctx, q.getProgramCodeAtRevisionStmt, getProgramCodeAtRevision, arg.ProgramUuid, arg.Revision)
	var code []byte
	err := row.Scan(&code)
	return code, err
}

const getSignedProgramCodeAtHead = `-- name: GetSignedProgramCodeAtHead :one
SELECT
	code, revision
FROM program_code_revisions
WHERE program_uuid = $1
AND signed IS NOT NULL
ORDER BY revision DESC
LIMIT 1
`

type GetSignedProgramCodeAtHeadRow struct {
	Code     []byte
	Revision int32
}

func (q *Queries) GetSignedProgramCodeAtHead(ctx context.Context, programUuid uuid.UUID) (GetSignedProgramCodeAtHeadRow, error) {
	row := q.queryRow(ctx, q.getSignedProgramCodeAtHeadStmt, getSignedProgramCodeAtHead, programUuid)
	var i GetSignedProgramCodeAtHeadRow
	err := row.Scan(&i.Code, &i.Revision)
	return i, err
}

const signProgramCodeRevision = `-- name: SignProgramCodeRevision :execrows
UPDATE program_code_revisions
SET signed_by = $1, signed = now()
WHERE program_uuid = $2
AND revision = $3
`

type SignProgramCodeRevisionParams struct {
	SignedBy    uuid.NullUUID
	ProgramUuid uuid.UUID
	Revision    int32
}

func (q *Queries) SignProgramCodeRevision(ctx context.Context, arg SignProgramCodeRevisionParams) (int64, error) {
	result, err := q.exec(ctx, q.signProgramCodeRevisionStmt, signProgramCodeRevision, arg.SignedBy, arg.ProgramUuid, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateProgramByUUID = `-- name: UpdateProgramByUUID :execrows
UPDATE programs
SET
	name = CASE
		WHEN $1::boolean THEN $2
		ELSE name
	END,
	type = CASE
		WHEN $3::boolean THEN $4
		ELSE type
	END,
	state = CASE
		WHEN $5::boolean THEN $6
		ELSE state
	END,
	schedule = CASE
		WHEN $7::boolean THEN $8
		ELSE schedule
	END,
	deadline = CASE
		WHEN $9::boolean THEN $10
		ELSE deadline
	END,
	language = CASE
		WHEN $11::boolean THEN $12
		ELSE language
	END,
	tags = CASE
		WHEN $13::boolean THEN $14
		ELSE tags
	END
WHERE programs.uuid = $15
`

type UpdateProgramByUUIDParams struct {
	SetName     bool
	Name        string
	SetType     bool
	Type        string
	SetState    bool
	State       string
	SetSchedule bool
	Schedule    string
	SetDeadline bool
	Deadline    int32
	SetLanguage bool
	Language    string
	SetTags     bool
	Tags        []string
	Uuid        uuid.UUID
}

func (q *Queries) UpdateProgramByUUID(ctx context.Context, arg UpdateProgramByUUIDParams) (int64, error) {
	result, err := q.exec(ctx, q.updateProgramByUUIDStmt, updateProgramByUUID,
		arg.SetName,
		arg.Name,
		arg.SetType,
		arg.Type,
		arg.SetState,
		arg.State,
		arg.SetSchedule,
		arg.Schedule,
		arg.SetDeadline,
		arg.Deadline,
		arg.SetLanguage,
		arg.Language,
		arg.SetTags,
		pq.Array(arg.Tags),
		arg.Uuid,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
