// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addTokenToUser = `-- name: AddTokenToUser :one
INSERT INTO user_tokens(user_uuid, name, token_hash)
SELECT users.uuid, $1, sha256($2)
FROM users
WHERE users.uuid = $3
RETURNING uuid, user_uuid, name, token_hash, created
`

type AddTokenToUserParams struct {
	Name     string
	Secret   []byte
	UserUuid uuid.UUID
}

func (q *Queries) AddTokenToUser(ctx context.Context, arg AddTokenToUserParams) (UserToken, error) {
	row := q.queryRow(ctx, q.addTokenToUserStmt, addTokenToUser, arg.Name, arg.Secret, arg.UserUuid)
	var i UserToken
	err := row.Scan(
		&i.Uuid,
		&i.UserUuid,
		&i.Name,
		&i.TokenHash,
		&i.Created,
	)
	return i, err
}

const addUserToGroup = `-- name: AddUserToGroup :exec
INSERT INTO user_groups(user_uuid, group_uuid)
VALUES(
	$1::uuid,
	$2::uuid
)
`

type AddUserToGroupParams struct {
	UserUuid  uuid.UUID
	GroupUuid uuid.UUID
}

func (q *Queries) AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) error {
	_, err := q.exec(ctx, q.addUserToGroupStmt, addUserToGroup, arg.UserUuid, arg.GroupUuid)
	return err
}

const addUserToGroups = `-- name: AddUserToGroups :execrows
INSERT INTO user_groups(user_uuid, group_uuid)
SELECT users.uuid, input.group_uuid
FROM users
INNER JOIN UNNEST($1::uuid[]) AS input(group_uuid) ON TRUE
WHERE users.uuid = $2
`

type AddUserToGroupsParams struct {
	GroupUuids []uuid.UUID
	UserUuid   uuid.UUID
}

func (q *Queries) AddUserToGroups(ctx context.Context, arg AddUserToGroupsParams) (int64, error) {
	result, err := q.exec(ctx, q.addUserToGroupsStmt, addUserToGroups, pq.Array(arg.GroupUuids), arg.UserUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createUser = `-- name: CreateUser :one
WITH grp AS (
	INSERT INTO groups(name)
	VALUES($1)
	RETURNING uuid, name
), usr AS (
	INSERT INTO users(name)
	VALUES($1)
	RETURNING uuid, name, state
), grp_policies AS (
	INSERT INTO group_policies(group_uuid, priority, effect, action, resource)
	VALUES (
		(SELECT uuid FROM grp), 0, 'allow', 'read','users/me'
	), (

		(SELECT uuid FROM grp), 0, 'allow', 'create','users/'||(SELECT uuid FROM usr)
	), (
		(SELECT uuid FROM grp), 0, 'allow', 'read','users/'||(SELECT uuid FROM usr)
	), (
		(SELECT uuid FROM grp), 0, 'allow', 'update','users/'||(SELECT uuid FROM usr)
	), (
		(SELECT uuid FROM grp), 0, 'allow', 'delete','users/'||(SELECT uuid FROM usr)
	), (

		(SELECT uuid FROM grp), 0, 'allow', 'create','users/'||(SELECT uuid FROM usr)||'/%'
	), (
		(SELECT uuid FROM grp), 0, 'allow', 'read','users/'||(SELECT uuid FROM usr)||'/%'
	), (
		(SELECT uuid FROM grp), 0, 'allow', 'update','users/'||(SELECT uuid FROM usr)||'/%'
	), (
		(SELECT uuid FROM grp), 0, 'allow', 'delete','users/'||(SELECT uuid FROM usr)||'/%'
	), (
		(SELECT uuid FROM grp), 0, 'deny', 'update','users/'||(SELECT uuid FROM usr)||'/rate'
	)
), usrgrp AS (
	INSERT INTO user_groups(user_uuid, group_uuid)
	SELECT usr.uuid, grp.uuid
	FROM usr, grp
)
SELECT uuid, name, state FROM usr
`

type CreateUserRow struct {
	Uuid  uuid.UUID
	Name  string
	State AccountState
}

func (q *Queries) CreateUser(ctx context.Context, name string) (CreateUserRow, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser, name)
	var i CreateUserRow
	err := row.Scan(&i.Uuid, &i.Name, &i.State)
	return i, err
}

const deleteTokenFromUser = `-- name: DeleteTokenFromUser :execrows
DELETE FROM user_tokens
WHERE user_tokens.uuid = $1
AND user_tokens.user_uuid = $2
`

type DeleteTokenFromUserParams struct {
	TokenUuid uuid.UUID
	UserUuid  uuid.UUID
}

func (q *Queries) DeleteTokenFromUser(ctx context.Context, arg DeleteTokenFromUserParams) (int64, error) {
	result, err := q.exec(ctx, q.deleteTokenFromUserStmt, deleteTokenFromUser, arg.TokenUuid, arg.UserUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteUser = `-- name: DeleteUser :execrows
WITH grp AS (
	DELETE FROM groups
	WHERE name = (
		SELECT name
		FROM users
		WHERE users.uuid = $1
	)
)
DELETE FROM users
WHERE users.uuid = $1
`

func (q *Queries) DeleteUser(ctx context.Context, argUuid uuid.UUID) (int64, error) {
	result, err := q.exec(ctx, q.deleteUserStmt, deleteUser, argUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const existsUser = `-- name: ExistsUser :one
SELECT COUNT(*) AS count
FROM users
WHERE users.uuid = $1
`

func (q *Queries) ExistsUser(ctx context.Context, argUuid uuid.UUID) (int64, error) {
	row := q.queryRow(ctx, q.existsUserStmt, existsUser, argUuid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findTokensByUser = `-- name: FindTokensByUser :many
SELECT uuid, name, created
FROM user_tokens
WHERE user_tokens.user_uuid = $1
`

type FindTokensByUserRow struct {
	Uuid    uuid.UUID
	Name    string
	Created time.Time
}

func (q *Queries) FindTokensByUser(ctx context.Context, argUuid uuid.UUID) ([]FindTokensByUserRow, error) {
	rows, err := q.query(ctx, q.findTokensByUserStmt, findTokensByUser, argUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindTokensByUserRow{}
	for rows.Next() {
		var i FindTokensByUserRow
		if err := rows.Scan(&i.Uuid, &i.Name, &i.Created); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUserByUUID = `-- name: FindUserByUUID :one
SELECT uuid, name, state
FROM users
WHERE users.uuid = $1
LIMIT 1
`

func (q *Queries) FindUserByUUID(ctx context.Context, argUuid uuid.UUID) (User, error) {
	row := q.queryRow(ctx, q.findUserByUUIDStmt, findUserByUUID, argUuid)
	var i User
	err := row.Scan(&i.Uuid, &i.Name, &i.State)
	return i, err
}

const findUserWithGroupsByToken = `-- name: FindUserWithGroupsByToken :one
SELECT
	users.uuid, users.name, users.state,
	(COALESCE((
		SELECT json_agg(json_build_object('uuid', groups.uuid, 'name', groups.name))
		FROM user_groups
		INNER JOIN groups ON groups.uuid = user_groups.group_uuid
		WHERE users.uuid = user_groups.user_uuid
	), '[]')::text) AS groups
FROM users
INNER JOIN user_tokens ON user_tokens.user_uuid = users.uuid
WHERE user_tokens.token_hash = sha256($1)
LIMIT 1
`

type FindUserWithGroupsByTokenRow struct {
	Uuid   uuid.UUID
	Name   string
	State  AccountState
	Groups string
}

func (q *Queries) FindUserWithGroupsByToken(ctx context.Context, token []byte) (FindUserWithGroupsByTokenRow, error) {
	row := q.queryRow(ctx, q.findUserWithGroupsByTokenStmt, findUserWithGroupsByToken, token)
	var i FindUserWithGroupsByTokenRow
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.State,
		&i.Groups,
	)
	return i, err
}

const findUserWithGroupsByUUID = `-- name: FindUserWithGroupsByUUID :one
SELECT
	users.uuid, users.name, users.state,
	(COALESCE((
		SELECT json_agg(json_build_object('uuid', groups.uuid, 'name', groups.name))
		FROM user_groups
		INNER JOIN groups ON groups.uuid = user_groups.group_uuid
		WHERE users.uuid = user_groups.user_uuid
	), '[]')::text) AS groups
FROM users
WHERE users.uuid = $1
LIMIT 1
`

type FindUserWithGroupsByUUIDRow struct {
	Uuid   uuid.UUID
	Name   string
	State  AccountState
	Groups string
}

func (q *Queries) FindUserWithGroupsByUUID(ctx context.Context, argUuid uuid.UUID) (FindUserWithGroupsByUUIDRow, error) {
	row := q.queryRow(ctx, q.findUserWithGroupsByUUIDStmt, findUserWithGroupsByUUID, argUuid)
	var i FindUserWithGroupsByUUIDRow
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.State,
		&i.Groups,
	)
	return i, err
}

const findUsers = `-- name: FindUsers :many
WITH usr AS (
	SELECT user_tokens.user_uuid AS uuid
	FROM user_tokens
	WHERE user_tokens.token_hash = sha256($1)
	LIMIT 1
), partial_users AS (
	SELECT uuid, name, state
	FROM users
	WHERE EXISTS (
		SELECT 1
		FROM usr
		INNER JOIN user_groups ON user_groups.user_uuid = usr.uuid
		INNER JOIN group_policies ON group_policies.group_uuid = user_groups.group_uuid
		WHERE group_policies.action = 'read'
		AND group_policies.effect = 'allow'
		AND ('users/'||users.uuid) LIKE group_policies.resource
	)
	AND NOT EXISTS (
		SELECT 1
		FROM usr
		INNER JOIN user_groups ON user_groups.user_uuid = usr.uuid
		INNER JOIN group_policies ON group_policies.group_uuid = user_groups.group_uuid
		WHERE group_policies.action = 'read'
		AND group_policies.effect = 'deny'
		AND ('users/'||users.uuid) LIKE group_policies.resource
	)
	ORDER BY name
	LIMIT $3::BIGINT
	OFFSET $2::BIGINT
)
SELECT partial_users.uuid, partial_users.name, partial_users.state, (COALESCE((
	SELECT json_agg(json_build_object('uuid', groups.uuid, 'name', groups.name))
	FROM user_groups, groups
	WHERE groups.uuid = user_groups.group_uuid
	AND partial_users.uuid = user_groups.user_uuid
), '[]')::text) AS groups
FROM partial_users
`

type FindUsersParams struct {
	Token     []byte
	ArgOffset int64
	ArgLimit  int64
}

type FindUsersRow struct {
	Uuid   uuid.UUID
	Name   string
	State  AccountState
	Groups string
}

func (q *Queries) FindUsers(ctx context.Context, arg FindUsersParams) ([]FindUsersRow, error) {
	rows, err := q.query(ctx, q.findUsersStmt, findUsers, arg.Token, arg.ArgOffset, arg.ArgLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindUsersRow{}
	for rows.Next() {
		var i FindUsersRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.State,
			&i.Groups,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserUuidFromToken = `-- name: GetUserUuidFromToken :one
SELECT user_tokens.user_uuid AS uuid
FROM user_tokens
WHERE user_tokens.token_hash = sha256($1)
LIMIT 1
`

func (q *Queries) GetUserUuidFromToken(ctx context.Context, token []byte) (uuid.UUID, error) {
	row := q.queryRow(ctx, q.getUserUuidFromTokenStmt, getUserUuidFromToken, token)
	var uuid uuid.UUID
	err := row.Scan(&uuid)
	return uuid, err
}

const removeUserFromAllGroups = `-- name: RemoveUserFromAllGroups :execrows
DELETE FROM user_groups
WHERE user_uuid = $1
`

func (q *Queries) RemoveUserFromAllGroups(ctx context.Context, userUuid uuid.UUID) (int64, error) {
	result, err := q.exec(ctx, q.removeUserFromAllGroupsStmt, removeUserFromAllGroups, userUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const removeUserFromGroups = `-- name: RemoveUserFromGroups :execrows
DELETE FROM user_groups
WHERE user_uuid = $1
AND group_uuid = ANY($2::uuid[])
`

type RemoveUserFromGroupsParams struct {
	UserUuid   uuid.UUID
	GroupUuids []uuid.UUID
}

func (q *Queries) RemoveUserFromGroups(ctx context.Context, arg RemoveUserFromGroupsParams) (int64, error) {
	result, err := q.exec(ctx, q.removeUserFromGroupsStmt, removeUserFromGroups, arg.UserUuid, pq.Array(arg.GroupUuids))
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setUserName = `-- name: SetUserName :execrows
UPDATE users SET name = $1
WHERE uuid = $2
`

type SetUserNameParams struct {
	Name string
	Uuid uuid.UUID
}

func (q *Queries) SetUserName(ctx context.Context, arg SetUserNameParams) (int64, error) {
	result, err := q.exec(ctx, q.setUserNameStmt, setUserName, arg.Name, arg.Uuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
